using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace xPlannerAPI.Tests.Repositories
{
    class ConsolidatedQueryResults
    {
        public static string[] groupBy1 = {"resp", "type_resp", "project_id", "asset_id", "asset_domain_id", "asset_code", "estimated_delivery_date", "cad_id",
            "asset_description", "manufacturer_description", "cut_sheet", "cad_block", "serial_number", "serial_name", "revit", "photo", "photo_domain_id", "tag_photo", "photo_rotate", 
            "discontinued", "cost_center", "cost_center_id", "current_location", "tag", "comment", "domain_id", "none_option", "quote_number", "vendor", "po_requested_number", 
            "medgas", "medgas_option", "medgas_oxygen", "medgas_air", "medgas_n2o", "medgas_co2", "medgas_wag", "medgas_other", "medgas_high_pressure", 
            "medgas_nitrogen", "medgas_vacuum", "medgas_steam", "medgas_natgas", 
            "gas_liquid_co2", "gas_liquid_nitrogen", "gas_instrument_air", "gas_liquid_propane_gas", "gas_methane", "gas_butane", "gas_propane", "gas_hydrogen", "gas_acetylene", 
            "misc_antimicrobial", "misc_ecolabel", "misc_ecolabel_desc", "biomed_check_required", 
            "plumbing", "plumbing_option", "plu_hot_water", "plu_cold_water", "plu_drain", "plu_return", "plu_treated_water", 
            "plu_chilled_water", "plu_relief", "water", "water_option", "cfm", "btus", 
            "electrical", "electrical_option", "volts", "phases", "hertz", "amps", "volt_amps", "watts", "connection_type", "plug_type", 
            "blocking", "blocking_option", "supports", "supports_option", "misc_seismic", 
            "misc_ase", "misc_ada", "misc_shielding_lead_line", "misc_shielding_magnetic", "mobile", "mobile_option", "height", "width", "depth", "mounting_height", "clearance_top", "clearance_bottom", 
            "clearance_right", "clearance_left", "clearance_front", "clearance_back", "weight", "loaded_weight", "ship_weight", 
            "data_desc", "data_option", "lan", " network_type", " network_option", 
            "linked_template", "asset_profile", "profile_tooltip", "profile_text", "profile_budget", 
            "detailed_budget", "linked_document", "pdoc_blob_filename", "pdoc_filename", "has_shop_drawing", "total_unit_budget", "lead_time", 
            "ports", "bluetooth", "cat6", "displayport", "dvi", "hdmi", "wireless", "class", "jsn_code", "jsn_description", "jsn_comments", "jsn_nomenclature", 
            "jsn_utility1", "jsn_utility2", "jsn_utility3", "jsn_utility4", "jsn_utility5", "jsn_utility6", 
            "blueprint", "functional_area", " room_area", "room_code", "staff", "clin", "source_location", "target_location", "source_room", "target_room", 
            "unit_markup", "unit_escalation", "unit_freight_net", "unit_freight_markup", "unit_install_net",
            "unit_install_markup", "unit_tax", "ECN", "placement", "temporary_location", "final_disposition", "delivered_date", "received_date" };

        public const string expectedResult1 = @"SELECT resp, type_resp, project_id, asset_id, asset_domain_id, asset_code, estimated_delivery_date, cad_id, asset_description, manufacturer_description, 
cut_sheet, cad_block, serial_number, serial_name, revit, photo, photo_domain_id, tag_photo, photo_rotate, discontinued, cost_center, cost_center_id, current_location, 
tag, comment, domain_id, none_option, quote_number, vendor, po_requested_number, medgas, medgas_option, medgas_oxygen, medgas_air, medgas_n2o, medgas_co2, medgas_wag, 
medgas_other, medgas_high_pressure, medgas_nitrogen, medgas_vacuum, medgas_steam, medgas_natgas, gas_liquid_co2, gas_liquid_nitrogen, gas_instrument_air, 
gas_liquid_propane_gas, gas_methane, gas_butane, gas_propane, gas_hydrogen, gas_acetylene, misc_antimicrobial, misc_ecolabel, misc_ecolabel_desc, biomed_check_required, 
plumbing, plumbing_option, plu_hot_water, plu_cold_water, plu_drain, plu_return, plu_treated_water, plu_chilled_water, plu_relief, water, water_option, cfm, btus, 
electrical, electrical_option, volts, phases, hertz, amps, volt_amps, watts, connection_type, plug_type, blocking, blocking_option, supports, supports_option, misc_seismic, 
misc_ase, misc_ada, misc_shielding_lead_line, misc_shielding_magnetic, mobile, mobile_option, height, width, depth, mounting_height, clearance_top, clearance_bottom, 
clearance_right, clearance_left, clearance_front, clearance_back, weight, loaded_weight, ship_weight, data_desc, data_option, lan,  network_type,  network_option, 
linked_template, asset_profile, profile_tooltip, profile_text, profile_budget, detailed_budget, linked_document, pdoc_blob_filename, pdoc_filename, has_shop_drawing, 
total_unit_budget, lead_time, ports, bluetooth, cat6, displayport, dvi, hdmi, wireless, class, jsn_code, jsn_description, jsn_comments, jsn_nomenclature, jsn_utility1, 
jsn_utility2, jsn_utility3, jsn_utility4, jsn_utility5, jsn_utility6, blueprint, functional_area,  room_area, room_code, staff, clin, source_location, target_location, 
source_room, target_room, unit_markup, unit_escalation, unit_freight_net, unit_freight_markup, unit_install_net, unit_install_markup, unit_tax, ECN, placement, 
temporary_location, final_disposition, delivered_date, received_date, 1 as consolidated_view,'' as option_ids, 0.00 as unit_budget,  
CASE WHEN 1 >= 2 THEN phase_id ELSE 0 END AS phase_id, CASE WHEN 1 >= 3 THEN department_id ELSE 0 END AS department_id, 
CASE WHEN 1 = 4 THEN room_id ELSE 0 END AS room_id,  COUNT(*) AS quantity, STRING_AGG(CAST(phase_id AS VARCHAR(MAX)), ',') as phases_qty,  
STRING_AGG(CAST(department_id AS VARCHAR(MAX)), ',') as departments_qty, STRING_AGG(CAST(room_id AS VARCHAR(MAX)), ',') as rooms_qty,  
(SELECT COUNT(asset_option_id) FROM assets_options ao WHERE ao.asset_id = a.asset_id AND ao.domain_id = a.asset_domain_id) as total_assets_options , 
STRING_AGG(inventory_id, ',') as inventory_id, MIN(project_description) as project_description, MIN(phase_description) as phase_description, 
MIN(department_description) as department_description, MIN(room_number) as room_number, MIN(room_name) as room_name, MIN(final_room_number) as final_room_number, 
MIN(final_room_name) as final_room_name, MIN(room_count) as room_count, SUM(COALESCE(budget_qty, 0)) AS budget_qty, SUM(COALESCE(dnp_qty, 0)) AS dnp_qty,
SUM(COALESCE(lease_qty, 0)) AS lease_qty, SUM(COALESCE(po_qty, 0)) AS po_qty, SUM(COALESCE(asset_total_budget, 0)) AS asset_total_budget,
CAST(SUM(CAST(options_price AS FLOAT)) AS VARCHAR(15)) as options_price, SUM(COALESCE(total_budget_amt, 0)) AS total_budget_amt,
SUM(COALESCE(total_po_amt, 0)) AS total_po_amt, SUM(COALESCE(buyout_delta, 0)) AS buyout_delta, SUM(COALESCE(net_new, 0)) AS net_new,
STRING_AGG(po_status, ',') as po_status, SUM(COALESCE(po_status_none, 0)) AS po_status_none, SUM(COALESCE(po_status_open, 0)) AS po_status_open,
SUM(COALESCE(po_status_issued, 0)) AS po_status_issued, SUM(COALESCE(po_status_requested, 0)) AS po_status_requested,
SUM(COALESCE(po_status_qreceived, 0)) AS po_status_qreceived, SUM(COALESCE(po_status_qrequested, 0)) AS po_status_qrequested, CAST(MIN(volts_ow + 0) AS BIT) as volts_ow, 
CAST(MIN(amps_ow+0) AS BIT) as amps_ow, CAST(MIN(connection_type_ow+0) AS BIT) as connection_type_ow, CAST(MIN(plug_type_ow+0) AS BIT) as plug_type_ow, 
CAST(MIN(height_ow+0) AS BIT) as height_ow, CAST(MIN(width_ow+0) AS BIT) as width_ow, CAST(MIN(depth_ow+0) AS BIT) as depth_ow, 
CAST(MIN(mounting_height_ow+0) AS BIT) as mounting_height_ow, CAST(MIN(lan_ow+0) AS BIT) as lan_ow, STRING_AGG(network_type, ',') as network_type, 
CAST(MIN(network_type_ow+0) AS BIT) as network_type_ow, SUM(COALESCE(network_option, 0)) AS network_option, CAST(MIN(network_option_ow + 0) AS BIT) as network_option_ow, 
CAST(MIN(ports_ow+0) AS BIT) as ports_ow, CAST(MIN(bluetooth_ow+0) AS BIT) as bluetooth_ow, CAST(MIN(cat6_ow+0) AS BIT) as cat6_ow, 
CAST(MIN(displayport_ow+0) AS BIT) as displayport_ow, CAST(MIN(dvi_ow+0) AS BIT) as dvi_ow, CAST(MIN(hdmi_ow+0) AS BIT) as hdmi_ow, 
CAST(MIN(wireless_ow+0) AS BIT) as wireless_ow, SUM(COALESCE(it_connections, 0)) AS it_connections, STRING_AGG(option_codes, ',') as option_codes, 
STRING_AGG(option_descriptions, ',') as option_descriptions, (SELECT DBO.FN_REMOVE_DUPLICATED_ITEMS(STRING_AGG(po_number, ','))) as po_number, 
CAST(MIN(class_ow+0) AS BIT) as class_ow, SUM(COALESCE(room_area, 0)) AS room_area, SUM(COALESCE(unit_markup_calc, 0)) AS unit_markup_calc,
SUM(COALESCE(unit_escalation_calc, 0)) AS unit_escalation_calc, SUM(COALESCE(unit_budget_adjusted, 0)) AS unit_budget_adjusted,
SUM(COALESCE(unit_tax_calc, 0)) AS unit_tax_calc, SUM(COALESCE(unit_install, 0)) AS unit_install, SUM(COALESCE(unit_freight, 0)) AS unit_freight,
SUM(COALESCE(unit_budget_total, 0)) AS unit_budget_total, SUM(COALESCE(total_install_net, 0)) AS total_install_net,
SUM(COALESCE(total_budget_adjusted, 0)) AS total_budget_adjusted, SUM(COALESCE(total_tax, 0)) AS total_tax, SUM(COALESCE(total_install, 0)) AS total_install,
SUM(COALESCE(total_freight_net, 0)) AS total_freight_net, SUM(COALESCE(total_freight, 0)) AS total_freight, SUM(COALESCE(total_budget, 0)) AS total_budget,
CAST(MIN(placement_ow + 0) AS BIT) as placement_ow, CAST(MIN(asset_description_ow+0) AS BIT) as asset_description_ow, CAST(MIN(jsn_ow+0) AS BIT) as jsn_ow, 
CAST(MIN(manufacturer_description_ow+0) AS BIT) as manufacturer_description_ow, CAST(MIN(serial_number_ow+0) AS BIT) as serial_number_ow, 
CAST(MIN(serial_name_ow+0) AS BIT) as serial_name_ow, MIN(date_modified) as date_modified
FROM asset_inventory a  WHERE project_id = 746 AND domain_id = 5
GROUP BY resp, type_resp, project_id, asset_id, asset_domain_id, asset_code, estimated_delivery_date, cad_id, asset_description, 
manufacturer_description, cut_sheet, cad_block, serial_number, serial_name, revit, photo, photo_domain_id, tag_photo, photo_rotate, discontinued, 
cost_center, cost_center_id, current_location, tag, comment, domain_id, none_option, quote_number, vendor, po_requested_number, medgas, medgas_option, 
medgas_oxygen, medgas_air, medgas_n2o, medgas_co2, medgas_wag, medgas_other, medgas_high_pressure, medgas_nitrogen, medgas_vacuum, medgas_steam, medgas_natgas, 
gas_liquid_co2, gas_liquid_nitrogen, gas_instrument_air, gas_liquid_propane_gas, gas_methane, gas_butane, gas_propane, gas_hydrogen, gas_acetylene, 
misc_antimicrobial, misc_ecolabel, misc_ecolabel_desc, biomed_check_required, plumbing, plumbing_option, plu_hot_water, plu_cold_water, plu_drain, 
plu_return, plu_treated_water, plu_chilled_water, plu_relief, water, water_option, cfm, btus, electrical, electrical_option, volts, phases, hertz, 
amps, volt_amps, watts, connection_type, plug_type, blocking, blocking_option, supports, supports_option, misc_seismic, misc_ase, misc_ada, misc_shielding_lead_line, 
misc_shielding_magnetic, mobile, mobile_option, height, width, depth, mounting_height, clearance_top, clearance_bottom, clearance_right, clearance_left, 
clearance_front, clearance_back, weight, loaded_weight, ship_weight, data_desc, data_option, lan,  network_type,  network_option, linked_template, asset_profile, 
profile_tooltip, profile_text, profile_budget, detailed_budget, linked_document, pdoc_blob_filename, pdoc_filename, has_shop_drawing, total_unit_budget, 
lead_time, ports, bluetooth, cat6, displayport, dvi, hdmi, wireless, class, jsn_code, jsn_description, jsn_comments, jsn_nomenclature, jsn_utility1, jsn_utility2, 
jsn_utility3, jsn_utility4, jsn_utility5, jsn_utility6, blueprint, functional_area,  room_area, room_code, staff, clin, source_location, target_location, source_room, 
target_room, unit_markup, unit_escalation, unit_freight_net, unit_freight_markup, unit_install_net, unit_install_markup, unit_tax, ECN, placement, temporary_location, 
final_disposition, delivered_date, received_date";

        public static string[] groupByWithoutTag = {"resp", "type_resp", "project_id", "asset_id", "asset_domain_id", "asset_code", "estimated_delivery_date", "cad_id",
            "asset_description", "manufacturer_description", "cut_sheet", "cad_block", "serial_number", "serial_name", "revit", "photo", "photo_domain_id", "tag_photo", "photo_rotate",
            "discontinued", "cost_center", "cost_center_id", "current_location", "comment", "domain_id", "none_option", "quote_number", "vendor", "po_requested_number",
            "medgas", "medgas_option", "medgas_oxygen", "medgas_air", "medgas_n2o", "medgas_co2", "medgas_wag", "medgas_other", "medgas_high_pressure",
            "medgas_nitrogen", "medgas_vacuum", "medgas_steam", "medgas_natgas",
            "gas_liquid_co2", "gas_liquid_nitrogen", "gas_instrument_air", "gas_liquid_propane_gas", "gas_methane", "gas_butane", "gas_propane", "gas_hydrogen", "gas_acetylene",
            "misc_antimicrobial", "misc_ecolabel", "misc_ecolabel_desc", "biomed_check_required",
            "plumbing", "plumbing_option", "plu_hot_water", "plu_cold_water", "plu_drain", "plu_return", "plu_treated_water",
            "plu_chilled_water", "plu_relief", "water", "water_option", "cfm", "btus",
            "electrical", "electrical_option", "volts", "phases", "hertz", "amps", "volt_amps", "watts", "connection_type", "plug_type",
            "blocking", "blocking_option", "supports", "supports_option", "misc_seismic",
            "misc_ase", "misc_ada", "misc_shielding_lead_line", "misc_shielding_magnetic", "mobile", "mobile_option", "height", "width", "depth", "mounting_height", "clearance_top", "clearance_bottom",
            "clearance_right", "clearance_left", "clearance_front", "clearance_back", "weight", "loaded_weight", "ship_weight",
            "data_desc", "data_option", "lan", " network_type", " network_option",
            "linked_template", "asset_profile", "profile_tooltip", "profile_text", "profile_budget",
            "detailed_budget", "linked_document", "pdoc_blob_filename", "pdoc_filename", "has_shop_drawing", "total_unit_budget", "lead_time",
            "ports", "bluetooth", "cat6", "displayport", "dvi", "hdmi", "wireless", "class", "jsn_code", "jsn_description", "jsn_comments", "jsn_nomenclature",
            "jsn_utility1", "jsn_utility2", "jsn_utility3", "jsn_utility4", "jsn_utility5", "jsn_utility6",
            "blueprint", "functional_area", " room_area", "room_code", "staff", "clin", "source_location", "target_location", "source_room", "target_room",
            "unit_markup", "unit_escalation", "unit_freight_net", "unit_freight_markup", "unit_install_net",
            "unit_install_markup", "unit_tax", "ECN", "placement", "temporary_location", "final_disposition", "delivered_date", "received_date" };

        public static string[] groupByWithoutTagResp = { "type_resp", "project_id", "asset_id", "asset_domain_id", "asset_code", "estimated_delivery_date", "cad_id",
            "asset_description", "manufacturer_description", "cut_sheet", "cad_block", "serial_number", "serial_name", "revit", "photo", "photo_domain_id", "tag_photo", "photo_rotate",
            "discontinued", "cost_center", "cost_center_id", "current_location", "comment", "domain_id", "none_option", "quote_number", "vendor", "po_requested_number",
            "medgas", "medgas_option", "medgas_oxygen", "medgas_air", "medgas_n2o", "medgas_co2", "medgas_wag", "medgas_other", "medgas_high_pressure",
            "medgas_nitrogen", "medgas_vacuum", "medgas_steam", "medgas_natgas",
            "gas_liquid_co2", "gas_liquid_nitrogen", "gas_instrument_air", "gas_liquid_propane_gas", "gas_methane", "gas_butane", "gas_propane", "gas_hydrogen", "gas_acetylene",
            "misc_antimicrobial", "misc_ecolabel", "misc_ecolabel_desc", "biomed_check_required",
            "plumbing", "plumbing_option", "plu_hot_water", "plu_cold_water", "plu_drain", "plu_return", "plu_treated_water",
            "plu_chilled_water", "plu_relief", "water", "water_option", "cfm", "btus",
            "electrical", "electrical_option", "volts", "phases", "hertz", "amps", "volt_amps", "watts", "connection_type", "plug_type",
            "blocking", "blocking_option", "supports", "supports_option", "misc_seismic",
            "misc_ase", "misc_ada", "misc_shielding_lead_line", "misc_shielding_magnetic", "mobile", "mobile_option", "height", "width", "depth", "mounting_height", "clearance_top", "clearance_bottom",
            "clearance_right", "clearance_left", "clearance_front", "clearance_back", "weight", "loaded_weight", "ship_weight",
            "data_desc", "data_option", "lan", " network_type", " network_option",
            "linked_template", "asset_profile", "profile_tooltip", "profile_text", "profile_budget",
            "detailed_budget", "linked_document", "pdoc_blob_filename", "pdoc_filename", "has_shop_drawing", "total_unit_budget", "lead_time",
            "ports", "bluetooth", "cat6", "displayport", "dvi", "hdmi", "wireless", "class", "jsn_code", "jsn_description", "jsn_comments", "jsn_nomenclature",
            "jsn_utility1", "jsn_utility2", "jsn_utility3", "jsn_utility4", "jsn_utility5", "jsn_utility6",
            "blueprint", "functional_area", " room_area", "room_code", "staff", "clin", "source_location", "target_location", "source_room", "target_room",
            "unit_markup", "unit_escalation", "unit_freight_net", "unit_freight_markup", "unit_install_net",
            "unit_install_markup", "unit_tax", "ECN", "placement", "temporary_location", "final_disposition", "delivered_date", "received_date" };

        public static string[] groupByWithoutTagRespCadId = { "type_resp", "project_id", "asset_id", "asset_domain_id", "asset_code", "estimated_delivery_date", 
            "asset_description", "manufacturer_description", "cut_sheet", "cad_block", "serial_number", "serial_name", "revit", "photo", "photo_domain_id", "tag_photo", "photo_rotate",
            "discontinued", "cost_center", "cost_center_id", "current_location", "comment", "domain_id", "none_option", "quote_number", "vendor", "po_requested_number",
            "medgas", "medgas_option", "medgas_oxygen", "medgas_air", "medgas_n2o", "medgas_co2", "medgas_wag", "medgas_other", "medgas_high_pressure",
            "medgas_nitrogen", "medgas_vacuum", "medgas_steam", "medgas_natgas",
            "gas_liquid_co2", "gas_liquid_nitrogen", "gas_instrument_air", "gas_liquid_propane_gas", "gas_methane", "gas_butane", "gas_propane", "gas_hydrogen", "gas_acetylene",
            "misc_antimicrobial", "misc_ecolabel", "misc_ecolabel_desc", "biomed_check_required",
            "plumbing", "plumbing_option", "plu_hot_water", "plu_cold_water", "plu_drain", "plu_return", "plu_treated_water",
            "plu_chilled_water", "plu_relief", "water", "water_option", "cfm", "btus",
            "electrical", "electrical_option", "volts", "phases", "hertz", "amps", "volt_amps", "watts", "connection_type", "plug_type",
            "blocking", "blocking_option", "supports", "supports_option", "misc_seismic",
            "misc_ase", "misc_ada", "misc_shielding_lead_line", "misc_shielding_magnetic", "mobile", "mobile_option", "height", "width", "depth", "mounting_height", "clearance_top", "clearance_bottom",
            "clearance_right", "clearance_left", "clearance_front", "clearance_back", "weight", "loaded_weight", "ship_weight",
            "data_desc", "data_option", "lan", " network_type", " network_option",
            "linked_template", "asset_profile", "profile_tooltip", "profile_text", "profile_budget",
            "detailed_budget", "linked_document", "pdoc_blob_filename", "pdoc_filename", "has_shop_drawing", "total_unit_budget", "lead_time",
            "ports", "bluetooth", "cat6", "displayport", "dvi", "hdmi", "wireless", "class", "jsn_code", "jsn_description", "jsn_comments", "jsn_nomenclature",
            "jsn_utility1", "jsn_utility2", "jsn_utility3", "jsn_utility4", "jsn_utility5", "jsn_utility6",
            "blueprint", "functional_area", " room_area", "room_code", "staff", "clin", "source_location", "target_location", "source_room", "target_room",
            "unit_markup", "unit_escalation", "unit_freight_net", "unit_freight_markup", "unit_install_net",
            "unit_install_markup", "unit_tax", "ECN", "placement", "temporary_location", "final_disposition", "delivered_date", "received_date" };


        public static string[] groupByReduced = { "resp", "asset_id", "asset_domain_id", "asset_code", "domain_id" };


        public static string[] groupByWithColumnsToIgnoreAndRequired = { "resp", "inventory_id", "consolidated_view", "option_ids", "unit_budget", "phase_id" };


        public static string[] groupByIncorrect = { "juliana", "lalalala" };
    }
}
