CREATE PROCEDURE [dbo].[split_rooms](
	@domain_id SMALLINT,
    @project_id INTEGER,
    @phase_id INTEGER,
    @department_id INTEGER,
	@from_domain_id SMALLINT,
    @from_project_id INTEGER,
    @from_phase_id INTEGER,
    @from_department_id INTEGER,
	@from_room_id INTEGER,
	@added_by VARCHAR(50),
	@is_linked_template BIT,
	@template_room_name CHARACTER VARYING(50) = null,
	@room_name CHARACTER VARYING(50) = null,
	@room_number CHARACTER VARYING(32) = null)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @return_var VARCHAR(500);
	DECLARE @template_id int, @linked_template bit;
	SET @return_var = '';
	SET @template_id = 0;
	SET @linked_template = 1;

	IF @is_linked_template = 1 BEGIN
		CREATE TABLE	#return_value(
			project_id	int,
			department_id	int,
			room_id	int,
			drawing_room_name	varchar	(50),
			drawing_room_number	varchar	(32),
			final_room_name	varchar	(50),
			final_room_number	varchar	(32),
			date_added	date,
			added_by	varchar	(50),
			comment	varchar	(1000),
			phase_id	int,
			domain_id	smallint,
			project_id_template	int,
			project_domain_id_template	smallint,
			applied_id_template	int,
			linked_template	bit,
			is_template	bit,
			department_type_id_template	int,
			department_type_domain_id_template	smallint,
			id	int,
			room_quantity	int, 
			room_code varchar(20), 
			room_area numeric(10,2), 
			blueprint varchar(50),
			staff varchar(50),
			functional_area varchar(50)
		)


		INSERT INTO #return_value EXEC create_template @from_domain_id, @from_project_id, @from_phase_id, @from_department_id, @from_room_id, @from_domain_id,
                 @template_room_name, @added_by, @from_domain_id, @from_project_id, true, 'Generated by split room functionality';

		SELECT	@template_id = id FROM #return_value;
		DROP TABLE #return_value;
	END

	IF @template_id = 0 BEGIN
		SET @template_id = null;
		SET @linked_template = null;
	END		
	
	EXEC copy_rooms @domain_id, @project_id, @phase_id, @department_id, @from_domain_id, @from_project_id, @from_phase_id, 
					@from_department_id, @from_room_id, @added_by, true, @room_name, @room_number, @template_id, 1, 0, 0, @return_var OUTPUT;

	update project_room set room_quantity = 1, applied_id_template = @template_id, linked_template = @linked_template
	where project_id = @from_project_id and phase_id = @from_phase_id and department_id = @from_department_id and room_id = @from_room_id and domain_id = @from_domain_id;




END