//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class box
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public box()
        {
            this.equipment_box = new HashSet<equipment_box>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> project_id { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<int> room_id { get; set; }
        public Nullable<int> max_jack_connections { get; set; }
        public Nullable<int> box_number { get; set; }
        public Nullable<int> connection_room_id { get; set; }
        public int phase_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipment_box> equipment_box { get; set; }
        public virtual project_room project_room { get; set; }
    }
}
