//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cad_domain
    {
        public int cad_domain_id { get; set; }
        public string domain { get; set; }
        public string cad_id { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string added_by { get; set; }
        public Nullable<int> equipment_id { get; set; }
        public Nullable<short> equipment_domain_id { get; set; }
    
        public virtual equipment equipment { get; set; }
    }
}
