//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cost_center
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cost_center()
        {
            this.project_room_relo_inventory = new HashSet<project_room_relo_inventory>();
            this.project_room_inventory = new HashSet<project_room_inventory>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public string description { get; set; }
        public int project_id { get; set; }
        public Nullable<bool> is_default { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_room_relo_inventory> project_room_relo_inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_room_inventory> project_room_inventory { get; set; }
        public virtual project project { get; set; }
    }
}
