//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipment_by_room
    {
        public int project_id { get; set; }
        public string project_description { get; set; }
        public string phase_description { get; set; }
        public string dept_description { get; set; }
        public string drawing_room_name { get; set; }
        public string drawing_room_number { get; set; }
        public string resp { get; set; }
        public Nullable<int> budget_qty { get; set; }
        public Nullable<int> dnp_qty { get; set; }
        public Nullable<int> lease_qty { get; set; }
        public Nullable<int> po_qty { get; set; }
        public string comment { get; set; }
        public int phase_id { get; set; }
        public int department_id { get; set; }
        public string equipment_desc { get; set; }
        public int equipment_id { get; set; }
        public string equipment_code { get; set; }
        public string serial_number { get; set; }
        public string comment2 { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<decimal> weight_kg { get; set; }
        public string hwd { get; set; }
        public Nullable<decimal> hwd_cm { get; set; }
        public string water_option { get; set; }
        public string plumbing_option { get; set; }
        public string data_option { get; set; }
        public string electrical_option { get; set; }
        public string mobile_option { get; set; }
        public string blocking_option { get; set; }
        public string medgas_option { get; set; }
        public string supports_option { get; set; }
        public string eq_unit_desc { get; set; }
        public Nullable<int> cost_center_id { get; set; }
        public short domain_id { get; set; }
        public string cad_id { get; set; }
        public string equipment_cad_desc { get; set; }
    }
}
