//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipment_drawing
    {
        public int project_id { get; set; }
        public int phase_id { get; set; }
        public int drawing_id { get; set; }
        public string filename { get; set; }
        public System.DateTime date_added { get; set; }
    
        public virtual project_phase project_phase { get; set; }
    }
}
