//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipment_category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public equipment_category()
        {
            this.equipment_subcategory = new HashSet<equipment_subcategory>();
        }
    
        public int category_id { get; set; }
        public string description { get; set; }
        public short domain_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipment_subcategory> equipment_subcategory { get; set; }
        public virtual domain domain { get; set; }
    }
}
