//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class equip_load
    {
        public string code { get; set; }
        public string description { get; set; }
        public string manufacturer { get; set; }
        public string category { get; set; }
        public string subcategory { get; set; }
        public string model { get; set; }
        public Nullable<double> height { get; set; }
        public Nullable<double> width { get; set; }
        public Nullable<double> depth { get; set; }
        public Nullable<double> weight { get; set; }
        public string responsibility { get; set; }
        public string hvac { get; set; }
        public string plumbing { get; set; }
        public string data { get; set; }
        public string electrical { get; set; }
        public string mobile { get; set; }
        public string blocking { get; set; }
        public string supports { get; set; }
        public string medgas { get; set; }
        public Nullable<double> unit_budget { get; set; }
        public string comments { get; set; }
    }
}
