//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public equipment()
        {
            this.cad_domain = new HashSet<cad_domain>();
            this.equipment_box = new HashSet<equipment_box>();
            this.template_equipment_box = new HashSet<template_equipment_box>();
            this.vendor_equipment = new HashSet<vendor_equipment>();
            this.equipment_options = new HashSet<equipment_options>();
            this.equipment_colors = new HashSet<equipment_colors>();
            this.equipment_box1 = new HashSet<equipment_box>();
            this.template_equipment_box1 = new HashSet<template_equipment_box>();
            this.template_room_inventory = new HashSet<template_room_inventory>();
            this.project_equipment = new HashSet<project_equipment>();
            this.equipment1 = new HashSet<equipment>();
            this.equipments = new HashSet<equipment>();
        }
    
        public int equipment_id { get; set; }
        public string equipment_code { get; set; }
        public int manufacturer_id { get; set; }
        public string equipment_desc { get; set; }
        public int subcategory_id { get; set; }
        public Nullable<decimal> height { get; set; }
        public Nullable<decimal> width { get; set; }
        public Nullable<decimal> depth { get; set; }
        public Nullable<decimal> weight { get; set; }
        public string serial_number { get; set; }
        public Nullable<decimal> min_cost { get; set; }
        public Nullable<decimal> max_cost { get; set; }
        public Nullable<decimal> avg_cost { get; set; }
        public Nullable<decimal> last_cost { get; set; }
        public string default_resp { get; set; }
        public string cut_sheet { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string added_by { get; set; }
        public string comment { get; set; }
        public string cad_block { get; set; }
        public string water { get; set; }
        public string plumbing { get; set; }
        public string data { get; set; }
        public string electrical { get; set; }
        public string mobile { get; set; }
        public string blocking { get; set; }
        public string medgas { get; set; }
        public string supports { get; set; }
        public string discontinued { get; set; }
        public Nullable<System.DateTime> last_budget_update { get; set; }
        public string photo { get; set; }
        public Nullable<int> eq_measurement_id { get; set; }
        public Nullable<int> water_option { get; set; }
        public Nullable<int> plumbing_option { get; set; }
        public Nullable<int> data_option { get; set; }
        public Nullable<int> electrical_option { get; set; }
        public Nullable<int> mobile_option { get; set; }
        public Nullable<int> blocking_option { get; set; }
        public Nullable<int> medgas_option { get; set; }
        public Nullable<int> supports_option { get; set; }
        public string revit { get; set; }
        public string placement { get; set; }
        public Nullable<decimal> clearance_left { get; set; }
        public Nullable<decimal> clearance_right { get; set; }
        public Nullable<decimal> clearance_front { get; set; }
        public Nullable<decimal> clearance_back { get; set; }
        public Nullable<decimal> clearance_top { get; set; }
        public Nullable<decimal> clearance_bottom { get; set; }
        public string volts { get; set; }
        public Nullable<int> phases { get; set; }
        public string hertz { get; set; }
        public string amps { get; set; }
        public Nullable<decimal> volt_amps { get; set; }
        public string watts { get; set; }
        public string cfm { get; set; }
        public string btus { get; set; }
        public Nullable<bool> misc_ase { get; set; }
        public Nullable<bool> misc_ada { get; set; }
        public Nullable<bool> misc_seismic { get; set; }
        public Nullable<bool> misc_antimicrobial { get; set; }
        public Nullable<bool> misc_ecolabel { get; set; }
        public string misc_ecolabel_desc { get; set; }
        public string mapping_code { get; set; }
        public Nullable<bool> medgas_oxygen { get; set; }
        public Nullable<bool> medgas_nitrogen { get; set; }
        public Nullable<bool> medgas_air { get; set; }
        public Nullable<bool> medgas_n2o { get; set; }
        public Nullable<bool> medgas_vacuum { get; set; }
        public Nullable<bool> medgas_wag { get; set; }
        public Nullable<bool> medgas_co2 { get; set; }
        public Nullable<bool> medgas_other { get; set; }
        public Nullable<bool> medgas_steam { get; set; }
        public Nullable<bool> medgas_natgas { get; set; }
        public Nullable<bool> plu_hot_water { get; set; }
        public Nullable<bool> plu_drain { get; set; }
        public Nullable<bool> plu_cold_water { get; set; }
        public Nullable<bool> plu_return { get; set; }
        public Nullable<bool> plu_treated_water { get; set; }
        public Nullable<bool> plu_relief { get; set; }
        public Nullable<bool> plu_chilled_water { get; set; }
        public string serial_name { get; set; }
        public Nullable<int> useful_life { get; set; }
        public Nullable<decimal> loaded_weight { get; set; }
        public Nullable<decimal> ship_weight { get; set; }
        public string alternate_equip { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public short domain_id { get; set; }
        public short manufacturer_domain_id { get; set; }
        public Nullable<bool> no_options { get; set; }
        public Nullable<bool> no_colors { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cad_domain> cad_domain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipment_box> equipment_box { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<template_equipment_box> template_equipment_box { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vendor_equipment> vendor_equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipment_options> equipment_options { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipment_colors> equipment_colors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipment_box> equipment_box1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<template_equipment_box> template_equipment_box1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<template_room_inventory> template_room_inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_equipment> project_equipment { get; set; }
        public virtual equipment_subcategory equipment_subcategory { get; set; }
        public virtual manufacturer manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipment> equipment1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipment> equipments { get; set; }
        public virtual domain domain { get; set; }
    }
}
