//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipment_box
    {
        public int id { get; set; }
        public int equipment_id { get; set; }
        public int box_id { get; set; }
        public string jack_number { get; set; }
        public Nullable<int> connected_equipment_id { get; set; }
        public short domain_id { get; set; }
        public Nullable<short> connected_domain_id { get; set; }
        public string added_by { get; set; }
    
        public virtual box box { get; set; }
        public virtual equipment equipment { get; set; }
        public virtual equipment equipment1 { get; set; }
    }
}
