//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_purchase_order
    {
        public int project_id { get; set; }
        public int department_id { get; set; }
        public int room_id { get; set; }
        public int equipment_id { get; set; }
        public int po_id { get; set; }
        public Nullable<int> po_qty { get; set; }
        public Nullable<decimal> po_unit_amt { get; set; }
        public string po_status { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string added_by { get; set; }
        public short domain_id { get; set; }
        public int phase_id { get; set; }
    
        public virtual project_room_inventory project_room_inventory { get; set; }
        public virtual purchase_order purchase_order { get; set; }
    }
}
