//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_po_qty_v
    {
        public int project_id { get; set; }
        public int phase_id { get; set; }
        public int department_id { get; set; }
        public int room_id { get; set; }
        public int equipment_id { get; set; }
        public Nullable<int> budget_qty { get; set; }
        public Nullable<int> budget_qty_sf { get; set; }
        public Nullable<decimal> total_budget_amt { get; set; }
        public Nullable<int> dnp_qty { get; set; }
        public Nullable<int> dnp_qty_sf { get; set; }
        public Nullable<int> po_qty { get; set; }
        public Nullable<int> po_qty_sf { get; set; }
        public Nullable<decimal> total_po_amt { get; set; }
        public Nullable<decimal> buyout_delta { get; set; }
        public string current_location { get; set; }
        public short domain_id { get; set; }
    }
}
