//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_status_v
    {
        public int project_id { get; set; }
        public int department_id { get; set; }
        public Nullable<int> item_quote_requested { get; set; }
        public Nullable<int> item_quote_received { get; set; }
        public Nullable<int> item_po_requested { get; set; }
        public Nullable<int> item_po_received { get; set; }
    }
}
