//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project_department()
        {
            this.project_room = new HashSet<project_room>();
        }
    
        public int project_id { get; set; }
        public int department_id { get; set; }
        public string description { get; set; }
        public int department_type_id { get; set; }
        public int phase_id { get; set; }
        public Nullable<int> area { get; set; }
        public string contact_name { get; set; }
        public string contact_email { get; set; }
        public string contact_phone { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string added_by { get; set; }
        public string comment { get; set; }
        public short department_type_domain_id { get; set; }
    
        public virtual department_type department_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_room> project_room { get; set; }
        public virtual project_phase project_phase { get; set; }
        public virtual domain domain { get; set; }
    }
}
