//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_room_inventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project_room_inventory()
        {
            this.inventory_purchase_order = new HashSet<inventory_purchase_order>();
        }
    
        public int project_id { get; set; }
        public int department_id { get; set; }
        public int room_id { get; set; }
        public int equipment_id { get; set; }
        public string status { get; set; }
        public string resp { get; set; }
        public Nullable<int> budget_qty { get; set; }
        public Nullable<int> relocate_qty { get; set; }
        public Nullable<int> dnp_qty { get; set; }
        public string relocate_comment { get; set; }
        public Nullable<decimal> unit_budget { get; set; }
        public Nullable<decimal> buyout_delta { get; set; }
        public Nullable<System.DateTime> estimated_delivery_date { get; set; }
        public string current_location { get; set; }
        public string location_comment { get; set; }
        public string inventory_type { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string added_by { get; set; }
        public string comment { get; set; }
        public Nullable<int> lease_qty { get; set; }
        public Nullable<int> cost_center_id { get; set; }
        public string tag { get; set; }
        public string cad_id { get; set; }
        public string equipment_option_ids { get; set; }
        public string equipment_color_ids { get; set; }
        public short domain_id { get; set; }
        public int phase_id { get; set; }
    
        public virtual cost_center cost_center { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventory_purchase_order> inventory_purchase_order { get; set; }
        public virtual project_room project_room { get; set; }
    }
}
