//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project()
        {
            this.cost_center = new HashSet<cost_center>();
            this.project_equipment = new HashSet<project_equipment>();
            this.project_phase = new HashSet<project_phase>();
            this.purchase_order = new HashSet<purchase_order>();
            this.relo_equipment = new HashSet<relo_equipment>();
            this.global_contact = new HashSet<global_contact>();
            this.AspNetUsers = new HashSet<AspNetUser>();
        }
    
        public int project_id { get; set; }
        public string project_description { get; set; }
        public Nullable<System.DateTime> project_start { get; set; }
        public Nullable<System.DateTime> project_end { get; set; }
        public string status { get; set; }
        public string client_project_number { get; set; }
        public string facility_project_number { get; set; }
        public string hsg_project_number { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string default_cost_field { get; set; }
        public Nullable<decimal> medial_budget { get; set; }
        public Nullable<decimal> freight_budget { get; set; }
        public Nullable<decimal> warehouse_budget { get; set; }
        public Nullable<decimal> tax_budget { get; set; }
        public Nullable<decimal> warranty_budget { get; set; }
        public Nullable<decimal> misc_budget { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string added_by { get; set; }
        public string comment { get; set; }
        public short domain_id { get; set; }
        public int client_id { get; set; }
        public short client_domain_id { get; set; }
        public int facility_id { get; set; }
        public short facility_domain_id { get; set; }
    
        public virtual client client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cost_center> cost_center { get; set; }
        public virtual facility facility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_equipment> project_equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_phase> project_phase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase_order> purchase_order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<relo_equipment> relo_equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<global_contact> global_contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
    }
}
