//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_phase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project_phase()
        {
            this.equipment_drawing = new HashSet<equipment_drawing>();
            this.project_department = new HashSet<project_department>();
        }
    
        public int project_id { get; set; }
        public int phase_id { get; set; }
        public string description { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public Nullable<System.DateTime> plan_end { get; set; }
        public Nullable<System.DateTime> plan_start { get; set; }
        public Nullable<System.DateTime> sd_date { get; set; }
        public Nullable<System.DateTime> dd_date { get; set; }
        public Nullable<System.DateTime> cd_date { get; set; }
        public Nullable<System.DateTime> equip_move_in_date { get; set; }
        public Nullable<System.DateTime> occupancy_date { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string added_by { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> ofci_delivery { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipment_drawing> equipment_drawing { get; set; }
        public virtual project project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_department> project_department { get; set; }
    }
}
