//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project_room()
        {
            this.boxes = new HashSet<box>();
            this.project_room_inventory = new HashSet<project_room_inventory>();
            this.project_room_relo_inventory = new HashSet<project_room_relo_inventory>();
        }
    
        public int project_id { get; set; }
        public int department_id { get; set; }
        public int room_id { get; set; }
        public string drawing_room_name { get; set; }
        public string drawing_room_number { get; set; }
        public string final_room_name { get; set; }
        public string final_room_number { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string added_by { get; set; }
        public string comment { get; set; }
        public int phase_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<box> boxes { get; set; }
        public virtual project_department project_department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_room_inventory> project_room_inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_room_relo_inventory> project_room_relo_inventory { get; set; }
    }
}
