//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_room_relo_inventory
    {
        public int project_id { get; set; }
        public int department_id { get; set; }
        public int room_id { get; set; }
        public int relo_id { get; set; }
        public string status { get; set; }
        public int qty { get; set; }
        public string resp { get; set; }
        public Nullable<System.DateTime> estimated_delivery_date { get; set; }
        public string current_location { get; set; }
        public string location_comment { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string added_by { get; set; }
        public string comment { get; set; }
        public Nullable<int> connection_room_id { get; set; }
        public Nullable<int> cost_center_id { get; set; }
        public string tag { get; set; }
        public int phase_id { get; set; }
    
        public virtual cost_center cost_center { get; set; }
        public virtual project_room project_room { get; set; }
        public virtual relo_equipment relo_equipment { get; set; }
    }
}
