//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class relo_equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public relo_equipment()
        {
            this.project_room_relo_inventory = new HashSet<project_room_relo_inventory>();
        }
    
        public int relo_id { get; set; }
        public string hsg_code { get; set; }
        public int project_id { get; set; }
        public string description { get; set; }
        public int department_type_id { get; set; }
        public string org_department { get; set; }
        public string org_room_number { get; set; }
        public string org_room_name { get; set; }
        public int qty { get; set; }
        public int manufacturer_id { get; set; }
        public string upc_hsg { get; set; }
        public string upc_biomed { get; set; }
        public string upc_facility { get; set; }
        public string upc_other { get; set; }
        public string upc_other_desc { get; set; }
        public string serial_number { get; set; }
        public int subcategory_id { get; set; }
        public string relocate { get; set; }
        public string condition_notes { get; set; }
        public string placement { get; set; }
        public string option_spec { get; set; }
        public string moving_note { get; set; }
        public string install_note { get; set; }
        public Nullable<decimal> height { get; set; }
        public Nullable<decimal> width { get; set; }
        public Nullable<decimal> depth { get; set; }
        public Nullable<decimal> weight { get; set; }
        public string water { get; set; }
        public string plumbing { get; set; }
        public string data { get; set; }
        public string electrical { get; set; }
        public string blocking { get; set; }
        public string medgas { get; set; }
        public string hvac { get; set; }
        public string btu_output { get; set; }
        public string oxygen { get; set; }
        public string air { get; set; }
        public string vacum { get; set; }
        public string wg { get; set; }
        public string co2 { get; set; }
        public string n2 { get; set; }
        public string compressed_air { get; set; }
        public string nitrogen { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string added_by { get; set; }
        public string comment { get; set; }
    
        public virtual project project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_room_relo_inventory> project_room_relo_inventory { get; set; }
    }
}
