//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class template_room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public template_room()
        {
            this.template_boxes = new HashSet<template_boxes>();
            this.template_room_inventory = new HashSet<template_room_inventory>();
        }
    
        public int template_room_id { get; set; }
        public int department_type_id { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string comment { get; set; }
        public short department_type_domain_id { get; set; }
    
        public virtual department_type department_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<template_boxes> template_boxes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<template_room_inventory> template_room_inventory { get; set; }
        public virtual domain domain { get; set; }
    }
}
