//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class template_boxes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public template_boxes()
        {
            this.template_equipment_box = new HashSet<template_equipment_box>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> template_room_id { get; set; }
        public Nullable<int> max_jack_connections { get; set; }
        public Nullable<int> box_number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<template_equipment_box> template_equipment_box { get; set; }
        public virtual template_room template_room { get; set; }
    }
}
