//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class template_room_inventory
    {
        public int template_room_id { get; set; }
        public int equipment_id { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public short domain_id { get; set; }
        public string added_by { get; set; }
    
        public virtual equipment equipment { get; set; }
        public virtual template_room template_room { get; set; }
    }
}
