//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendor_equipment
    {
        public int equipment_id { get; set; }
        public int vendor_id { get; set; }
        public Nullable<decimal> min_cost { get; set; }
        public Nullable<decimal> max_cost { get; set; }
        public Nullable<decimal> avg_cost { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string added_by { get; set; }
        public string comment { get; set; }
        public string model_number { get; set; }
        public short equipment_domain_id { get; set; }
        public short vendor_domain_id { get; set; }
        public Nullable<decimal> last_cost { get; set; }
    
        public virtual equipment equipment { get; set; }
        public virtual vendor vendor { get; set; }
    }
}
