//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendor_contact
    {
        public string name { get; set; }
        public int vendor_id { get; set; }
        public string contact_type { get; set; }
        public string title { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zipcode { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string added_by { get; set; }
        public string comment { get; set; }
        public string mobile { get; set; }
        public short vendor_domain_id { get; set; }
        public short contact_domain_id { get; set; }
    
        public virtual vendor vendor { get; set; }
    }
}
