//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerAPI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("xPlannerAPI.StringMessages", typeof(StringMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have at least one of these columns in the excel file: {0}.
        /// </summary>
        internal static string ImportAssetHintColumnMissing {
            get {
                return ResourceManager.GetString("ImportAssetHintColumnMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error to complete import. Status {0}, Error Message {1}..
        /// </summary>
        internal static string ImportCompletedError {
            get {
                return ResourceManager.GetString("ImportCompletedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import completed sucessfully. Please refresh your browser (Total Import time: {0:D2}min).
        /// </summary>
        internal static string ImportCompletedSuccess {
            get {
                return ResourceManager.GetString("ImportCompletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description {0} specified for the item is invalid. The category must be no longer than {1} chacarters..
        /// </summary>
        internal static string ImportDescriptionCategoryInvalid {
            get {
                return ResourceManager.GetString("ImportDescriptionCategoryInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description &apos;{0}&apos; specified for the item is invalid. The description must be in the format &apos;&lt;Category&gt;, &lt;Subcategory&gt;&apos;.
        /// </summary>
        internal static string ImportDescriptionInvalid {
            get {
                return ResourceManager.GetString("ImportDescriptionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description {0} specified for the item is invalid. The subcategory must be no longer than {1} chacarters..
        /// </summary>
        internal static string ImportDescriptionSubcategoryInvalid {
            get {
                return ResourceManager.GetString("ImportDescriptionSubcategoryInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file. The column &apos;{0}&apos; appears multiple times in the worksheet..
        /// </summary>
        internal static string ImportDuplicateColumn {
            get {
                return ResourceManager.GetString("ImportDuplicateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The worksheet specified is empty..
        /// </summary>
        internal static string ImportEmptyWorksheet {
            get {
                return ResourceManager.GetString("ImportEmptyWorksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importer exception: Message {0}, Stack {1}.
        /// </summary>
        internal static string ImporterException {
            get {
                return ResourceManager.GetString("ImporterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importer exceptoin: Message {0}, Inner Message {1}, Stack {2}.
        /// </summary>
        internal static string ImporterExceptionInner {
            get {
                return ResourceManager.GetString("ImporterExceptionInner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception happened while trying to import, please contact technical support..
        /// </summary>
        internal static string ImportExceptionError {
            get {
                return ResourceManager.GetString("ImportExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was generated during the import, please contact technical support [Item: {0}].
        /// </summary>
        internal static string ImportExceptionWithExceptionIndex {
            get {
                return ResourceManager.GetString("ImportExceptionWithExceptionIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for the field &apos;{0}&apos; has {1} characters and exceeds the maximum allowed of {2}.
        /// </summary>
        internal static string ImportFieldLimitExceeded {
            get {
                return ResourceManager.GetString("ImportFieldLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file specified could not be loaded.
        /// </summary>
        internal static string ImportFileCouldNotBeRead {
            get {
                return ResourceManager.GetString("ImportFileCouldNotBeRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file size exceeded the limit of {0} Mb..
        /// </summary>
        internal static string ImportFileSizeExceeded {
            get {
                return ResourceManager.GetString("ImportFileSizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system threw an exception during initialization, please contact technical support for details..
        /// </summary>
        internal static string ImportInitializationError {
            get {
                return ResourceManager.GetString("ImportInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The asset inventory id specified cannot be found in the existing inventory.
        /// </summary>
        internal static string ImportInvalidAssetId {
            get {
                return ResourceManager.GetString("ImportInvalidAssetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item cannot be imported because the value &apos;{0}&apos; for column &apos;{1}&apos; is invalid..
        /// </summary>
        internal static string ImportInvalidCellValue {
            get {
                return ResourceManager.GetString("ImportInvalidCellValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The class specified is invalid. The class must be one of the following: {0}.
        /// </summary>
        internal static string ImportInvalidClassSpecified {
            get {
                return ResourceManager.GetString("ImportInvalidClassSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project and enterprise specified could not be found.
        /// </summary>
        internal static string ImportInvalidDomainProject {
            get {
                return ResourceManager.GetString("ImportInvalidDomainProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file specified is invalid. Please make sure you specify a valid xlsx file. The importer does not support xls files..
        /// </summary>
        internal static string ImportInvalidFile {
            get {
                return ResourceManager.GetString("ImportInvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item {0} specified has errors and cannot be imported.
        /// </summary>
        internal static string ImportInvalidItemWithIndex {
            get {
                return ResourceManager.GetString("ImportInvalidItemWithIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Unit &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string ImportInvalidUnitOfMeasurement {
            get {
                return ResourceManager.GetString("ImportInvalidUnitOfMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have at least one of these fields per asset entry: {0}.
        /// </summary>
        internal static string ImportItemAssetHintColumnMissing {
            get {
                return ResourceManager.GetString("ImportItemAssetHintColumnMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The JSN &apos;{0}&apos; specified could not be found. A new JSN will be created in the Catalog..
        /// </summary>
        internal static string ImportJSNNotFound {
            get {
                return ResourceManager.GetString("ImportJSNNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The JSN suffix must have at most 4 characters.
        /// </summary>
        internal static string ImportJSNSuffixTooLong {
            get {
                return ResourceManager.GetString("ImportJSNSuffixTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The excel file specified exceeds the maximum number of supported rows.
        /// </summary>
        internal static string ImportMaxRows {
            get {
                return ResourceManager.GetString("ImportMaxRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching asset could be found and a new one cannot be created because no description or JSN Nomeclature has been specified..
        /// </summary>
        internal static string ImportMissingCategorySubcategory {
            get {
                return ResourceManager.GetString("ImportMissingCategorySubcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following mandatory fields are empty for this asset: {0}.
        /// </summary>
        internal static string ImportMissingItemRequiredColumns {
            get {
                return ResourceManager.GetString("ImportMissingItemRequiredColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column(s) &apos;{0}&apos; are mandatory and could not be found in the excel file. .
        /// </summary>
        internal static string ImportMissingRequiredColumns {
            get {
                return ResourceManager.GetString("ImportMissingRequiredColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The responsibility specified is invalid..
        /// </summary>
        internal static string ImportMissingResponsability {
            get {
                return ResourceManager.GetString("ImportMissingResponsability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple assets matching the specified values has been found. Please select one of them..
        /// </summary>
        internal static string ImportMultipleAssetsFound {
            get {
                return ResourceManager.GetString("ImportMultipleAssetsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error, no asset was returned for item {0}.
        /// </summary>
        internal static string ImportNoAssetReturnedWithIndex {
            get {
                return ResourceManager.GetString("ImportNoAssetReturnedWithIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No assets were found matching the specified values. The import will add a new entry to the catalog..
        /// </summary>
        internal static string ImportNoMatchingAssets {
            get {
                return ResourceManager.GetString("ImportNoMatchingAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; for placement is invalid.
        /// </summary>
        internal static string ImportPlacementInvalid {
            get {
                return ResourceManager.GetString("ImportPlacementInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import has processed {0} of {1} items..
        /// </summary>
        internal static string ImportStatusReport {
            get {
                return ResourceManager.GetString("ImportStatusReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{2}&apos; for JSN Utility {0}  does not match the value &apos;{1}&apos; found in the AudaxWare JSN Catalog.
        /// </summary>
        internal static string ImportUtilityAudaxWareMismatch {
            get {
                return ResourceManager.GetString("ImportUtilityAudaxWareMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{2}&apos; for JSN Utility {0}  does not match the value &apos;{1}&apos; found in your Enterprise JSN Catalog (created on previous imports).
        /// </summary>
        internal static string ImportUtilityDomainMismatch {
            get {
                return ResourceManager.GetString("ImportUtilityDomainMismatch", resourceCulture);
            }
        }
    }
}
