//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ancillary_v
    {
        public short domain_id { get; set; }
        public int project_id { get; set; }
        public Nullable<decimal> freight_budget { get; set; }
        public Nullable<decimal> freight_charges { get; set; }
        public Nullable<decimal> freight_projected { get; set; }
        public Nullable<decimal> warehouse_budget { get; set; }
        public Nullable<decimal> warehouse_charges { get; set; }
        public Nullable<decimal> warehouse_projected { get; set; }
        public Nullable<decimal> tax_budget { get; set; }
        public Nullable<decimal> tax_charges { get; set; }
        public Nullable<decimal> tax_projected { get; set; }
        public Nullable<decimal> misc_budget { get; set; }
        public Nullable<decimal> misc_charges { get; set; }
        public Nullable<decimal> misc_projected { get; set; }
        public Nullable<decimal> warranty_budget { get; set; }
        public Nullable<decimal> warranty_charges { get; set; }
        public Nullable<decimal> warranty_projected { get; set; }
        public Nullable<decimal> install_charges { get; set; }
        public Nullable<decimal> install_projected { get; set; }
        public Nullable<decimal> install_budget { get; set; }
        public Nullable<decimal> quote_discount { get; set; }
    }
}
