//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asset_summarized
    {
        public int asset_id { get; set; }
        public short domain_id { get; set; }
        public Nullable<bool> discontinued { get; set; }
        public string cut_sheet { get; set; }
        public string cad_block { get; set; }
        public string revit { get; set; }
        public string photo { get; set; }
        public string asset_code { get; set; }
        public string model_name { get; set; }
        public string model_number { get; set; }
        public string asset_description { get; set; }
        public Nullable<decimal> min_cost { get; set; }
        public Nullable<decimal> max_cost { get; set; }
        public Nullable<decimal> avg_cost { get; set; }
        public Nullable<decimal> last_cost { get; set; }
        public string default_resp { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string asset_suffix { get; set; }
        public string manufacturer_description { get; set; }
        public string owner_name { get; set; }
        public string asset_subcategory { get; set; }
        public string asset_category { get; set; }
        public string alternate_asset { get; set; }
        public string options_code { get; set; }
        public string vendors_model { get; set; }
        public string medgas { get; set; }
        public Nullable<int> medgas_option { get; set; }
        public Nullable<bool> medgas_oxygen { get; set; }
        public Nullable<bool> medgas_air { get; set; }
        public Nullable<bool> medgas_n2o { get; set; }
        public Nullable<bool> medgas_co2 { get; set; }
        public Nullable<bool> medgas_wag { get; set; }
        public Nullable<bool> medgas_other { get; set; }
        public Nullable<bool> medgas_nitrogen { get; set; }
        public Nullable<bool> medgas_vacuum { get; set; }
        public Nullable<bool> medgas_steam { get; set; }
        public Nullable<bool> medgas_natgas { get; set; }
        public Nullable<bool> gas_liquid_co2 { get; set; }
        public Nullable<bool> gas_liquid_nitrogen { get; set; }
        public Nullable<bool> gas_instrument_air { get; set; }
        public Nullable<bool> gas_liquid_propane_gas { get; set; }
        public Nullable<bool> gas_methane { get; set; }
        public Nullable<bool> gas_butane { get; set; }
        public Nullable<bool> gas_propane { get; set; }
        public Nullable<bool> gas_hydrogen { get; set; }
        public Nullable<bool> gas_acetylene { get; set; }
        public Nullable<bool> misc_antimicrobial { get; set; }
        public Nullable<bool> misc_ecolabel { get; set; }
        public string misc_ecolabel_desc { get; set; }
        public string plumbing { get; set; }
        public Nullable<int> plumbing_option { get; set; }
        public Nullable<bool> plu_hot_water { get; set; }
        public Nullable<bool> plu_cold_water { get; set; }
        public Nullable<bool> plu_drain { get; set; }
        public Nullable<bool> plu_return { get; set; }
        public Nullable<bool> plu_treated_water { get; set; }
        public Nullable<bool> plu_chilled_water { get; set; }
        public Nullable<bool> plu_relief { get; set; }
        public string water { get; set; }
        public Nullable<int> water_option { get; set; }
        public string cfm { get; set; }
        public string btus { get; set; }
        public string electrical { get; set; }
        public Nullable<int> electrical_option { get; set; }
        public string volts { get; set; }
        public Nullable<int> phases { get; set; }
        public string hertz { get; set; }
        public string amps { get; set; }
        public Nullable<decimal> volt_amps { get; set; }
        public string watts { get; set; }
        public string blocking { get; set; }
        public Nullable<int> blocking_option { get; set; }
        public string supports { get; set; }
        public Nullable<int> supports_option { get; set; }
        public Nullable<bool> misc_seismic { get; set; }
        public Nullable<bool> misc_ase { get; set; }
        public Nullable<bool> misc_ada { get; set; }
        public string mobile { get; set; }
        public Nullable<bool> misc_shielding_lead_line { get; set; }
        public Nullable<bool> misc_shielding_magnetic { get; set; }
        public Nullable<int> mobile_option { get; set; }
        public string height { get; set; }
        public string width { get; set; }
        public string depth { get; set; }
        public string mounting_height { get; set; }
        public Nullable<decimal> clearance_top { get; set; }
        public Nullable<decimal> clearance_bottom { get; set; }
        public Nullable<decimal> clearance_right { get; set; }
        public Nullable<decimal> clearance_left { get; set; }
        public Nullable<decimal> clearance_front { get; set; }
        public Nullable<decimal> clearance_back { get; set; }
        public string weight { get; set; }
        public Nullable<decimal> loaded_weight { get; set; }
        public Nullable<decimal> ship_weight { get; set; }
        public Nullable<int> data_option { get; set; }
        public string data_desc { get; set; }
        public Nullable<int> @class { get; set; }
        public string jsn_code { get; set; }
        public string jsn_description { get; set; }
        public string jsn_comments { get; set; }
        public string jsn_nomenclature { get; set; }
        public string jsn_utility1 { get; set; }
        public string jsn_utility2 { get; set; }
        public string jsn_utility3 { get; set; }
        public string jsn_utility4 { get; set; }
        public string jsn_utility5 { get; set; }
        public string jsn_utility6 { get; set; }
        public string jsn_utility7 { get; set; }
        public string imported_by_project { get; set; }
        public Nullable<bool> approval_pending { get; set; }
        public short manufacturer_domain_id { get; set; }
        public int manufacturer_id { get; set; }
        public Nullable<bool> approval_modify_aw_asset { get; set; }
        public string connection_type { get; set; }
        public string plug_type { get; set; }
        public Nullable<int> lan { get; set; }
        public string network_type { get; set; }
        public Nullable<int> network_option { get; set; }
        public Nullable<decimal> ports { get; set; }
        public Nullable<bool> bluetooth { get; set; }
        public Nullable<bool> cat6 { get; set; }
        public Nullable<bool> displayport { get; set; }
        public Nullable<bool> dvi { get; set; }
        public Nullable<bool> hdmi { get; set; }
        public Nullable<bool> wireless { get; set; }
    }
}
