//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asset_it_connectivity
    {
        public int connectivity_id { get; set; }
        public int project_id { get; set; }
        public short domain_id { get; set; }
        public int inventory_id_in { get; set; }
        public int inventory_id_out { get; set; }
        public string connection_type { get; set; }
        public string port_number { get; set; }
        public string comment { get; set; }
        public System.DateTime date_added { get; set; }
        public string added_by { get; set; }
        public string port_number_out { get; set; }
    
        public virtual project project { get; set; }
        public virtual project_room_inventory project_room_inventory { get; set; }
        public virtual project_room_inventory project_room_inventory1 { get; set; }
    }
}
