//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class assets_category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public assets_category()
        {
            this.assets_subcategory = new HashSet<assets_subcategory>();
        }
    
        public int category_id { get; set; }
        public string description { get; set; }
        public short domain_id { get; set; }
        public string Gases { get; set; }
        public string IT { get; set; }
        public string Electrical { get; set; }
        public string HVAC { get; set; }
        public string Plumbing { get; set; }
        public string Support { get; set; }
        public string Physical { get; set; }
        public string Environmental { get; set; }
        public string asset_code { get; set; }
        public Nullable<short> asset_code_domain_id { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string added_by { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assets_subcategory> assets_subcategory { get; set; }
        public virtual assets_codes assets_codes { get; set; }
        public virtual domain domain { get; set; }
    }
}
