//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class assets_project
    {
        public int asset_id { get; set; }
        public short asset_domain_id { get; set; }
        public int project_id { get; set; }
        public short domain_id { get; set; }
    
        public virtual asset asset { get; set; }
        public virtual project project { get; set; }
        public virtual domain domain { get; set; }
    }
}
