//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class assets_options
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public assets_options()
        {
            this.inventory_options = new HashSet<inventory_options>();
        }
    
        public int asset_option_id { get; set; }
        public Nullable<int> asset_id { get; set; }
        public string code { get; set; }
        public string description { get; set; }
        public string added_by { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public short domain_id { get; set; }
        public string data_type { get; set; }
        public Nullable<decimal> min_cost { get; set; }
        public Nullable<decimal> max_cost { get; set; }
        public Nullable<decimal> avg_cost { get; set; }
        public Nullable<decimal> last_cost { get; set; }
        public Nullable<decimal> unit_budget { get; set; }
        public Nullable<int> old_id { get; set; }
        public string display_code { get; set; }
        public Nullable<short> asset_domain_id { get; set; }
        public Nullable<short> project_domain_id { get; set; }
        public Nullable<int> project_id { get; set; }
        public Nullable<int> document_id { get; set; }
        public Nullable<short> document_domain_id { get; set; }
        public string settings { get; set; }
        public Nullable<int> scope { get; set; }
    
        public virtual asset asset { get; set; }
        public virtual project project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventory_options> inventory_options { get; set; }
        public virtual domain_document domain_document { get; set; }
        public virtual asset_option_scope asset_option_scope { get; set; }
    }
}
