//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AudaxWarePowerBI
    {
        public string Project { get; set; }
        public string Project_Status { get; set; }
        public string Phase { get; set; }
        public string Department { get; set; }
        public string Room_Number { get; set; }
        public string Room_Name { get; set; }
        public string Responsability { get; set; }
        public string Resp_Type { get; set; }
        public string Project_ID { get; set; }
        public string Phase_ID { get; set; }
        public string Department_ID { get; set; }
        public string Room_ID { get; set; }
        public string Asset_Code { get; set; }
        public string CAD_ID { get; set; }
        public string Asset_Description { get; set; }
        public string Manufacturer_Description { get; set; }
        public Nullable<int> Budget_Qty { get; set; }
        public Nullable<int> Do_Not_Purchase_Qty { get; set; }
        public Nullable<int> Lease_Qty { get; set; }
        public Nullable<int> PO_Qty { get; set; }
        public Nullable<decimal> Total_Budget_Amount { get; set; }
        public Nullable<decimal> Total_PO_Amount { get; set; }
        public Nullable<decimal> Buyout_Delta { get; set; }
        public Nullable<decimal> Total_Locked_Cost_Amount { get; set; }
        public string Model_Number { get; set; }
        public string Model_Name { get; set; }
        public string Discontinued { get; set; }
        public Nullable<int> Net_New { get; set; }
        public string Cost_Center { get; set; }
        public string PO_Status { get; set; }
        public string Current_Location { get; set; }
        public string Tag { get; set; }
        public Nullable<decimal> Unit_Budget { get; set; }
        public Nullable<System.DateTime> Estimated_Delivery_Date { get; set; }
        public string Comment { get; set; }
        public string Department_Type { get; set; }
        public Nullable<int> Department_Area { get; set; }
        public short Domain_ID { get; set; }
        public string PO_Number { get; set; }
        public string PO_Vendor { get; set; }
        public Nullable<decimal> Unit_Markup__ { get; set; }
        public Nullable<decimal> Unit_Escalation__ { get; set; }
        public Nullable<decimal> Unit_Tax__ { get; set; }
        public Nullable<decimal> Unit_Install_Markup { get; set; }
        public Nullable<decimal> Unit_Install__Net_ { get; set; }
        public Nullable<decimal> Unit_Freight_Markup { get; set; }
        public Nullable<decimal> Unit_Freight__Net_ { get; set; }
    }
}
