//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bundle_asset
    {
        public short bundle_domain_id { get; set; }
        public int bundle_id { get; set; }
        public short asset_domain_id { get; set; }
        public int asset_id { get; set; }
        public int asset_qty { get; set; }
    
        public virtual bundle bundle { get; set; }
        public virtual asset asset { get; set; }
    }
}
