//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bundle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bundle()
        {
            this.bundle_asset = new HashSet<bundle_asset>();
            this.bundle_inventory = new HashSet<bundle_inventory>();
        }
    
        public short domain_id { get; set; }
        public int bundle_id { get; set; }
        public string name { get; set; }
        public Nullable<short> project_domain_id { get; set; }
        public Nullable<int> project_id { get; set; }
        public string added_by { get; set; }
        public System.DateTime date_added { get; set; }
        public string comment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bundle_asset> bundle_asset { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bundle_inventory> bundle_inventory { get; set; }
        public virtual project project { get; set; }
        public virtual domain domain { get; set; }
    }
}
