//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dashboard
    {
        public int dashboard_id { get; set; }
        public short domain_id { get; set; }
        public string workspace_collection { get; set; }
        public string workspace_id { get; set; }
        public string dataset_id { get; set; }
        public string name { get; set; }
        public string report_id { get; set; }
        public Nullable<int> linked_dashboard_id { get; set; }
        public string pb_filename { get; set; }
    
        public virtual domain domain { get; set; }
    }
}
