//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class document_types
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public document_types()
        {
            this.inventory_documents = new HashSet<inventory_documents>();
            this.domain_document = new HashSet<domain_document>();
            this.project_documents = new HashSet<project_documents>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> display_level { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventory_documents> inventory_documents { get; set; }
        public virtual documents_display_levels documents_display_levels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<domain_document> domain_document { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_documents> project_documents { get; set; }
    }
}
