//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class documents_associations
    {
        public int id { get; set; }
        public short project_domain_id { get; set; }
        public int project_id { get; set; }
        public int document_id { get; set; }
        public Nullable<int> phase_id { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<int> room_id { get; set; }
        public Nullable<int> inventory_id { get; set; }
        public Nullable<short> asset_domain_id { get; set; }
        public Nullable<int> asset_id { get; set; }
        public string added_by { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
    
        public virtual asset asset { get; set; }
        public virtual project_documents project_documents { get; set; }
        public virtual project project { get; set; }
        public virtual project_room_inventory project_room_inventory { get; set; }
    }
}
