//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class domain_document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public domain_document()
        {
            this.assets_options = new HashSet<assets_options>();
            this.inventory_options = new HashSet<inventory_options>();
        }
    
        public int id { get; set; }
        public short domain_id { get; set; }
        public string filename { get; set; }
        public int type_id { get; set; }
        public System.DateTime date_added { get; set; }
        public string blob_file_name { get; set; }
        public string file_extension { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assets_options> assets_options { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventory_options> inventory_options { get; set; }
        public virtual document_types document_types { get; set; }
        public virtual domain domain { get; set; }
    }
}
