//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPMENT_INVENTORY_TMP
    {
        public int project_id { get; set; }
        public int phase_id { get; set; }
        public int department_id { get; set; }
        public int room_id { get; set; }
        public int asset_id { get; set; }
        public short asset_domain_id { get; set; }
        public string asset_code { get; set; }
        public string asset_description { get; set; }
        public string manufacturer_description { get; set; }
        public Nullable<long> budget_qty { get; set; }
        public Nullable<long> dnp_qty { get; set; }
        public Nullable<long> relocate_qty { get; set; }
        public Nullable<long> lease_qty { get; set; }
        public Nullable<decimal> po_qty { get; set; }
        public Nullable<decimal> total_budget_amt { get; set; }
        public Nullable<decimal> total_po_amt { get; set; }
        public Nullable<decimal> buyout_delta { get; set; }
        public string cut_sheet { get; set; }
        public string cad_block { get; set; }
        public string serial_number { get; set; }
        public string serial_name { get; set; }
        public string revit { get; set; }
        public string discontinued { get; set; }
        public Nullable<int> net_new { get; set; }
    }
}
