//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class full_project_name
    {
        public string project { get; set; }
        public int inventory_id { get; set; }
        public Nullable<int> inventory_source_id { get; set; }
        public string room { get; set; }
    }
}
