//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_documents
    {
        public int id { get; set; }
        public string filename { get; set; }
        public int type_id { get; set; }
        public short inventory_domain_id { get; set; }
        public int inventory_id { get; set; }
        public System.DateTime date_added { get; set; }
    
        public virtual document_types document_types { get; set; }
        public virtual project_room_inventory project_room_inventory { get; set; }
    }
}
