//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_options
    {
        public int inventory_id { get; set; }
        public int option_id { get; set; }
        public short domain_id { get; set; }
        public Nullable<decimal> unit_price { get; set; }
        public int quantity { get; set; }
        public Nullable<short> inventory_domain_id { get; set; }
        public Nullable<int> document_id { get; set; }
        public Nullable<short> document_domain_id { get; set; }
    
        public virtual assets_options assets_options { get; set; }
        public virtual domain_document domain_document { get; set; }
        public virtual project_room_inventory project_room_inventory { get; set; }
    }
}
