//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class joined_category_subcategory
    {
        public string description { get; set; }
        public short subcategory_domain_id { get; set; }
        public short category_domain_id { get; set; }
        public int category_id { get; set; }
        public int subcategory_id { get; set; }
        public Nullable<short> asset_code_domain { get; set; }
        public string asset_code { get; set; }
    }
}
