//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jsn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public jsn()
        {
            this.assets = new HashSet<asset>();
        }
    
        public int Id { get; set; }
        public short domain_id { get; set; }
        public string jsn_code { get; set; }
        public string nomenclature { get; set; }
        public string mhs_cat { get; set; }
        public string va_cat { get; set; }
        public string fundsourmhs { get; set; }
        public string fundsourva { get; set; }
        public Nullable<int> amps1 { get; set; }
        public Nullable<int> amps2 { get; set; }
        public Nullable<bool> archived { get; set; }
        public string assigned_individual { get; set; }
        public Nullable<int> btuperhour { get; set; }
        public Nullable<int> cen_depth { get; set; }
        public Nullable<decimal> cen_height { get; set; }
        public Nullable<decimal> cen_width { get; set; }
        public string comments { get; set; }
        public Nullable<System.DateTime> date_appr { get; set; }
        public string description { get; set; }
        public Nullable<int> freq_review { get; set; }
        public string hertz { get; set; }
        public string hertz_dep { get; set; }
        public string hertz_swit { get; set; }
        public Nullable<decimal> in_depth { get; set; }
        public Nullable<decimal> inches_height { get; set; }
        public Nullable<decimal> inches_width { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public string nsn { get; set; }
        public Nullable<bool> pending { get; set; }
        public Nullable<int> phase1 { get; set; }
        public Nullable<int> phase2 { get; set; }
        public string unit_issue { get; set; }
        public string utility1 { get; set; }
        public string utility2 { get; set; }
        public string utility3 { get; set; }
        public string utility4 { get; set; }
        public string utility5 { get; set; }
        public string utility6 { get; set; }
        public string utility7 { get; set; }
        public string volts { get; set; }
        public string watts { get; set; }
        public string wct_csi_link { get; set; }
        public Nullable<decimal> weight_av { get; set; }
        public Nullable<decimal> weight_met { get; set; }
        public string year_review { get; set; }
        public string asset_code { get; set; }
        public Nullable<short> asset_code_domain_id { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string added_by { get; set; }
        public Nullable<bool> deprecated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asset> assets { get; set; }
        public virtual domain domain { get; set; }
    }
}
