//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class matching_values
    {
        public short domain_id { get; set; }
        public int project_id { get; set; }
        public string total_projected { get; set; }
        public string project_budget { get; set; }
        public string projected_delta { get; set; }
        public string total_planned { get; set; }
        public string cliente_budget_delta { get; set; }
    }
}
