//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_room_inventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project_room_inventory()
        {
            this.asset_it_connectivity = new HashSet<asset_it_connectivity>();
            this.asset_it_connectivity1 = new HashSet<asset_it_connectivity>();
            this.bundle_inventory = new HashSet<bundle_inventory>();
            this.documents_associations = new HashSet<documents_associations>();
            this.inventory_documents = new HashSet<inventory_documents>();
            this.inventory_options = new HashSet<inventory_options>();
            this.inventory_purchase_order = new HashSet<inventory_purchase_order>();
        }
    
        public int project_id { get; set; }
        public int department_id { get; set; }
        public int room_id { get; set; }
        public int asset_id { get; set; }
        public string status { get; set; }
        public string resp { get; set; }
        public Nullable<int> budget_qty { get; set; }
        public Nullable<int> dnp_qty { get; set; }
        public Nullable<decimal> unit_budget { get; set; }
        public Nullable<decimal> buyout_delta { get; set; }
        public Nullable<System.DateTime> estimated_delivery_date { get; set; }
        public string current_location { get; set; }
        public string inventory_type { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string added_by { get; set; }
        public string comment { get; set; }
        public Nullable<int> lease_qty { get; set; }
        public Nullable<int> cost_center_id { get; set; }
        public string tag { get; set; }
        public string cad_id { get; set; }
        public Nullable<bool> none_option { get; set; }
        public short domain_id { get; set; }
        public int phase_id { get; set; }
        public short asset_domain_id { get; set; }
        public int inventory_id { get; set; }
        public string option_ids { get; set; }
        public Nullable<decimal> locked_unit_budget { get; set; }
        public Nullable<int> locked_budget_qty { get; set; }
        public Nullable<int> locked_dnp_qty { get; set; }
        public decimal options_unit_price { get; set; }
        public Nullable<decimal> options_price { get; set; }
        public Nullable<decimal> asset_total_budget { get; set; }
        public Nullable<decimal> total_budget_amt { get; set; }
        public Nullable<int> linked_id_template { get; set; }
        public string asset_profile { get; set; }
        public string asset_profile_budget { get; set; }
        public bool detailed_budget { get; set; }
        public Nullable<int> locked_room_quantity { get; set; }
        public Nullable<int> linked_document { get; set; }
        public Nullable<int> lead_time { get; set; }
        public string clin { get; set; }
        public Nullable<int> inventory_source_id { get; set; }
        public Nullable<int> inventory_target_id { get; set; }
        public Nullable<decimal> unit_markup { get; set; }
        public Nullable<decimal> unit_escalation { get; set; }
        public Nullable<decimal> unit_tax { get; set; }
        public Nullable<decimal> unit_install_net { get; set; }
        public Nullable<decimal> unit_install_markup { get; set; }
        public Nullable<decimal> unit_freight_net { get; set; }
        public Nullable<decimal> unit_freight_markup { get; set; }
        public Nullable<decimal> total_unit_budget { get; set; }
        public Nullable<decimal> unit_markup_calc { get; set; }
        public Nullable<decimal> unit_escalation_calc { get; set; }
        public Nullable<decimal> unit_budget_adjusted { get; set; }
        public Nullable<decimal> unit_tax_calc { get; set; }
        public Nullable<decimal> unit_install { get; set; }
        public Nullable<decimal> unit_freight { get; set; }
        public Nullable<decimal> unit_budget_total { get; set; }
        public Nullable<decimal> total_install_net { get; set; }
        public Nullable<decimal> total_budget_adjusted { get; set; }
        public Nullable<decimal> total_tax { get; set; }
        public Nullable<decimal> total_install { get; set; }
        public Nullable<decimal> total_freight_net { get; set; }
        public Nullable<decimal> total_freight { get; set; }
        public Nullable<decimal> total_budget { get; set; }
        public Nullable<int> net_new { get; set; }
        public Nullable<bool> asset_description_ow { get; set; }
        public string asset_description { get; set; }
        public string ECN { get; set; }
        public Nullable<bool> placement_ow { get; set; }
        public string placement { get; set; }
        public Nullable<bool> biomed_check_required { get; set; }
        public string temporary_location { get; set; }
        public Nullable<bool> height_ow { get; set; }
        public string height { get; set; }
        public Nullable<bool> width_ow { get; set; }
        public string width { get; set; }
        public Nullable<bool> depth_ow { get; set; }
        public string depth { get; set; }
        public Nullable<bool> mounting_height_ow { get; set; }
        public string mounting_height { get; set; }
        public Nullable<bool> class_ow { get; set; }
        public Nullable<int> @class { get; set; }
        public string jsn_code { get; set; }
        public string jsn_utility1 { get; set; }
        public string jsn_utility2 { get; set; }
        public string jsn_utility3 { get; set; }
        public string jsn_utility4 { get; set; }
        public string jsn_utility5 { get; set; }
        public string jsn_utility6 { get; set; }
        public string jsn_utility7 { get; set; }
        public Nullable<bool> update_trigger { get; set; }
        public System.Guid copy_link { get; set; }
        public Nullable<bool> jsn_ow { get; set; }
        public string manufacturer_description { get; set; }
        public Nullable<bool> manufacturer_description_ow { get; set; }
        public string serial_number { get; set; }
        public Nullable<bool> serial_number_ow { get; set; }
        public string serial_name { get; set; }
        public Nullable<bool> serial_name_ow { get; set; }
        public string cut_sheet_filename { get; set; }
        public string final_disposition { get; set; }
        public Nullable<System.DateTime> delivered_date { get; set; }
        public Nullable<System.DateTime> received_date { get; set; }
        public string connection_type { get; set; }
        public Nullable<bool> connection_type_ow { get; set; }
        public string plug_type { get; set; }
        public Nullable<bool> plug_type_ow { get; set; }
        public Nullable<int> lan { get; set; }
        public Nullable<bool> lan_ow { get; set; }
        public string network_type { get; set; }
        public Nullable<bool> network_type_ow { get; set; }
        public Nullable<int> network_option { get; set; }
        public Nullable<bool> network_option_ow { get; set; }
        public Nullable<decimal> ports { get; set; }
        public Nullable<bool> ports_ow { get; set; }
        public Nullable<bool> bluetooth { get; set; }
        public Nullable<bool> bluetooth_ow { get; set; }
        public Nullable<bool> cat6 { get; set; }
        public Nullable<bool> cat6_ow { get; set; }
        public Nullable<bool> displayport { get; set; }
        public Nullable<bool> displayport_ow { get; set; }
        public Nullable<bool> dvi { get; set; }
        public Nullable<bool> dvi_ow { get; set; }
        public Nullable<bool> hdmi { get; set; }
        public Nullable<bool> hdmi_ow { get; set; }
        public Nullable<bool> wireless { get; set; }
        public Nullable<bool> wireless_ow { get; set; }
        public string volts { get; set; }
        public Nullable<bool> volts_ow { get; set; }
        public string amps { get; set; }
        public Nullable<bool> amps_ow { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asset_it_connectivity> asset_it_connectivity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asset_it_connectivity> asset_it_connectivity1 { get; set; }
        public virtual asset asset { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bundle_inventory> bundle_inventory { get; set; }
        public virtual cost_center cost_center { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documents_associations> documents_associations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventory_documents> inventory_documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventory_options> inventory_options { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventory_purchase_order> inventory_purchase_order { get; set; }
        public virtual project_documents project_documents { get; set; }
        public virtual project_room project_room { get; set; }
    }
}
