//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_report
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project_report()
        {
            this.report_location = new HashSet<report_location>();
        }
    
        public int id { get; set; }
        public int report_type_id { get; set; }
        public short project_domain_id { get; set; }
        public int project_id { get; set; }
        public bool isPrivate { get; set; }
        public string generated_by { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public System.DateTime last_run { get; set; }
        public Nullable<int> cost_center { get; set; }
        public Nullable<bool> use_cad_id { get; set; }
        public Nullable<bool> include_cutsheets { get; set; }
        public Nullable<int> phase_id { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<int> room_id { get; set; }
        public string file_name { get; set; }
        public bool include_po_cover { get; set; }
        public bool include_po_uploaded { get; set; }
        public bool include_quote_uploaded { get; set; }
        public string po_status { get; set; }
        public decimal status { get; set; }
        public bool include_docs_without_link { get; set; }
        public bool include_budgets { get; set; }
        public bool include_jsn { get; set; }
        public bool include_code { get; set; }
        public bool include_total_budget { get; set; }
        public Nullable<int> compare_with_project_id { get; set; }
        public Nullable<bool> include_photo { get; set; }
        public string status_category { get; set; }
        public Nullable<bool> remove_logo { get; set; }
        public Nullable<bool> ignore_description_difference { get; set; }
        public Nullable<bool> remove_ecn { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual cost_center cost_center1 { get; set; }
        public virtual project project { get; set; }
        public virtual report_type report_type { get; set; }
        public virtual project_room project_room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<report_location> report_location { get; set; }
    }
}
