//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project()
        {
            this.assets_project = new HashSet<assets_project>();
            this.bundles = new HashSet<bundle>();
            this.cost_center = new HashSet<cost_center>();
            this.project_room = new HashSet<project_room>();
            this.user_project_mine = new HashSet<user_project_mine>();
            this.project_addresses = new HashSet<project_addresses>();
            this.project_phase = new HashSet<project_phase>();
            this.project_user = new HashSet<project_user>();
            this.global_contact = new HashSet<global_contact>();
            this.assets_options = new HashSet<assets_options>();
            this.temporary_location = new HashSet<temporary_location>();
            this.purchase_order = new HashSet<purchase_order>();
            this.final_disposition = new HashSet<final_disposition>();
            this.audit_log = new HashSet<audit_log>();
            this.documents_associations = new HashSet<documents_associations>();
            this.project_documents = new HashSet<project_documents>();
            this.asset_it_connectivity = new HashSet<asset_it_connectivity>();
            this.project_report = new HashSet<project_report>();
        }
    
        public int project_id { get; set; }
        public string project_description { get; set; }
        public Nullable<System.DateTime> project_start { get; set; }
        public Nullable<System.DateTime> project_end { get; set; }
        public string status { get; set; }
        public string client_project_number { get; set; }
        public string facility_project_number { get; set; }
        public string hsg_project_number { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string default_cost_field { get; set; }
        public Nullable<decimal> medial_budget { get; set; }
        public Nullable<decimal> freight_budget { get; set; }
        public Nullable<decimal> warehouse_budget { get; set; }
        public Nullable<decimal> tax_budget { get; set; }
        public Nullable<decimal> warranty_budget { get; set; }
        public Nullable<decimal> misc_budget { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string added_by { get; set; }
        public string comment { get; set; }
        public short domain_id { get; set; }
        public int client_id { get; set; }
        public short client_domain_id { get; set; }
        public int facility_id { get; set; }
        public short facility_domain_id { get; set; }
        public Nullable<decimal> markup { get; set; }
        public Nullable<decimal> escalation { get; set; }
        public Nullable<decimal> tax { get; set; }
        public Nullable<decimal> freight_markup { get; set; }
        public Nullable<decimal> install_markup { get; set; }
        public Nullable<decimal> markup_budget { get; set; }
        public Nullable<decimal> escalation_budget { get; set; }
        public Nullable<decimal> install_budget { get; set; }
        public Nullable<System.DateTime> date_locked { get; set; }
        public Nullable<int> from_project_id { get; set; }
        public string locked_comment { get; set; }
        public Nullable<System.DateTime> locked_date { get; set; }
        public System.Guid copy_link { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assets_project> assets_project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bundle> bundles { get; set; }
        public virtual client client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cost_center> cost_center { get; set; }
        public virtual facility facility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_room> project_room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_project_mine> user_project_mine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_addresses> project_addresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_phase> project_phase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_user> project_user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<global_contact> global_contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assets_options> assets_options { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<temporary_location> temporary_location { get; set; }
        public virtual domain domain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase_order> purchase_order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<final_disposition> final_disposition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<audit_log> audit_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documents_associations> documents_associations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_documents> project_documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asset_it_connectivity> asset_it_connectivity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_report> project_report { get; set; }
    }
}
