//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_user
    {
        public short project_domain_id { get; set; }
        public int project_id { get; set; }
        public string user_pid { get; set; }
        public int project_user_id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual project project { get; set; }
    }
}
