//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project_room()
        {
            this.purchase_order = new HashSet<purchase_order>();
            this.project_room_inventory = new HashSet<project_room_inventory>();
            this.project_report = new HashSet<project_report>();
        }
    
        public int project_id { get; set; }
        public int department_id { get; set; }
        public int room_id { get; set; }
        public string drawing_room_name { get; set; }
        public string drawing_room_number { get; set; }
        public string final_room_name { get; set; }
        public string final_room_number { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string added_by { get; set; }
        public string comment { get; set; }
        public int phase_id { get; set; }
        public short domain_id { get; set; }
        public Nullable<int> project_id_template { get; set; }
        public Nullable<short> project_domain_id_template { get; set; }
        public Nullable<int> applied_id_template { get; set; }
        public Nullable<bool> linked_template { get; set; }
        public Nullable<bool> is_template { get; set; }
        public Nullable<int> department_type_id_template { get; set; }
        public Nullable<short> department_type_domain_id_template { get; set; }
        public Nullable<int> id { get; set; }
        public int room_quantity { get; set; }
        public string room_code { get; set; }
        public Nullable<decimal> room_area { get; set; }
        public string blueprint { get; set; }
        public string staff { get; set; }
        public string functional_area { get; set; }
        public System.Guid copy_link { get; set; }
    
        public virtual department_type department_type { get; set; }
        public virtual project project { get; set; }
        public virtual project_department project_department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase_order> purchase_order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_room_inventory> project_room_inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_report> project_report { get; set; }
    }
}
