//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_documents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project_documents()
        {
            this.documents_associations = new HashSet<documents_associations>();
            this.project_room_inventory = new HashSet<project_room_inventory>();
        }
    
        public int id { get; set; }
        public string filename { get; set; }
        public int type_id { get; set; }
        public System.DateTime date_added { get; set; }
        public short project_domain_id { get; set; }
        public int project_id { get; set; }
        public string blob_file_name { get; set; }
        public string version { get; set; }
        public string status { get; set; }
        public string file_extension { get; set; }
        public string label { get; set; }
        public int rotate { get; set; }
        public string added_by { get; set; }
    
        public virtual document_types document_types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documents_associations> documents_associations { get; set; }
        public virtual project project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_room_inventory> project_room_inventory { get; set; }
    }
}
