//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public purchase_order()
        {
            this.vendor_contact = new HashSet<vendor_contact>();
            this.inventory_purchase_order = new HashSet<inventory_purchase_order>();
        }
    
        public int po_id { get; set; }
        public int project_id { get; set; }
        public string po_number { get; set; }
        public string quote_number { get; set; }
        public string description { get; set; }
        public int vendor_id { get; set; }
        public Nullable<System.DateTime> quote_requested_date { get; set; }
        public Nullable<System.DateTime> quote_received_date { get; set; }
        public Nullable<System.DateTime> po_requested_date { get; set; }
        public Nullable<System.DateTime> po_received_date { get; set; }
        public Nullable<decimal> freight { get; set; }
        public Nullable<decimal> warehouse { get; set; }
        public Nullable<decimal> tax { get; set; }
        public Nullable<decimal> warranty { get; set; }
        public Nullable<decimal> misc { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string added_by { get; set; }
        public string comment { get; set; }
        public string quote_file { get; set; }
        public string po_file { get; set; }
        public bool upd_asset_value { get; set; }
        public short vendor_domain_id { get; set; }
        public string po_requested_number { get; set; }
        public short domain_id { get; set; }
        public Nullable<int> ship_to { get; set; }
        public Nullable<int> phase_id { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<int> room_id { get; set; }
        public Nullable<decimal> quote_amount { get; set; }
        public Nullable<bool> allow_assets_update { get; set; }
        public Nullable<int> old_po_id { get; set; }
        public Nullable<decimal> install { get; set; }
        public System.Guid copy_link { get; set; }
        public bool invalid_po { get; set; }
        public Nullable<System.DateTime> quote_expiration_date { get; set; }
        public Nullable<decimal> quote_discount { get; set; }
    
        public virtual project project { get; set; }
        public virtual project_addresses project_addresses { get; set; }
        public virtual project_room project_room { get; set; }
        public virtual vendor vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vendor_contact> vendor_contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventory_purchase_order> inventory_purchase_order { get; set; }
    }
}
