//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xPlannerCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_gridView
    {
        public string user_id { get; set; }
        public string grid_state { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public int gridview_id { get; set; }
        public Nullable<int> sharedby_gridview_id { get; set; }
        public bool is_shared { get; set; }
        public short domain_id { get; set; }
        public bool is_private { get; set; }
        public string added_by { get; set; }
        public string consolidated_columns { get; set; }
    
        public virtual domain domain { get; set; }
    }
}
