xPlanner.constant('AssetInventoryColumns', {
    phase_description: 'Phase',
    department_description: 'Department',
    room_number: 'Room No.',
    room_name: 'Room Name',
    asset_code: 'Code',
    jsn_code: 'JSN',
    asset_description: 'Description',
    final_room_number: 'Wayfinding No.',
    final_room_name: 'Wayfinding Name',
    room_code: 'Room Code',
    blueprint: 'Blueprint',
    staff: 'Staff',
    room_area: 'Room Area',
    functional_area: 'Functional Area',
    resp: 'Resp',
    type_resp: 'Type',
    source_location: 'Source Location',
    target_location: 'Target Location',
    source_room: 'Source Room',
    target_room: 'Target Room',
    temporary_location: 'Temporary Location',
    final_disposition: 'Final Disposition',
    photo: 'Photo',
    tag_photo: 'Tag Photo',
    cad_id: 'CAD ID',
    serial_number: 'Model No.',
    serial_name: 'Model Name',
    manufacturer_description: 'Manufacturer',
    room_count: 'Room Count',
    budget_qty: 'Planned qty',
    medgas: 'Gases description',
    medgas_option: 'Gases required',
    medgas_oxygen: 'Oxygen',
    medgas_air: 'MedAir',
    medgas_n2o: 'N2O',
    medgas_co2: 'CO2',
    medgas_wag: 'WAG',
    medgas_other: 'Air Low Pressure',
    medgas_high_pressure: 'Air High Pressure',
    medgas_nitrogen: 'Nitrogen',
    medgas_vacuum: 'Vacuum',
    medgas_steam: 'Steam',
    medgas_natgas: 'NatGas',
    gas_acetylene: 'Acetylene',
    gas_butane: 'Butane',
    gas_hydrogen: 'Hydrogen',
    gas_instrument_air: 'Instrument Air',
    gas_liquid_co2: 'Liquid CO2',
    gas_liquid_nitrogen: 'Liquid Nitrogen',
    gas_liquid_propane_gas: 'Liquid Propane Gas',
    gas_methane: 'Methane',
    gas_propane: 'Propane',
    misc_antimicrobial: 'Antimicrobial',
    misc_ecolabel: 'Eco-Label',
    misc_ecolabel_desc: 'Eco-Label Description',
    plumbing: 'Pumbling Description',
    plumbing_option: 'Plumbing Required',
    plu_hot_water: 'Hot Water',
    plu_cold_water: 'Cold Water',
    plu_drain: 'Drain',
    plu_return: 'Return',
    plu_treated_water: 'Treated Water',
    plu_chilled_water: 'Chilled Water',
    plu_relief: 'Relief',
    water: 'Exhaust Description',
    water_option: 'Exhaust Required',
    cfm: 'CFM',
    btus: 'BTUs',
    data_desc: 'Data Description',
    data_option: 'Data Required',
    network_option: 'Network Required',
    network_type: 'Network Type',
    electrical: 'Electrical Description',
    electrical_option: 'Electrical Required',
    volts: 'Volts',
    phases: 'Phases',
    hertz: 'Hertz',
    amps: 'Amps',
    volt_amps: 'VoltAmps',
    watts: 'Watts',
    blocking: 'Blocking Description',
    blocking_option: 'Blocking Required',
    supports: 'Structural Description',
    supports_option: 'Structural Required',
    misc_seismic: 'Seismic Rated',
    misc_ase: 'ASE',
    misc_ada: 'ADA',
    misc_shielding_lead_line: 'Shielding, Lead Lined',
    misc_shielding_magnetic: 'Shielding, RF/Magnetic',
    mobile: 'Mobile Description',
    mobile_option: 'Mobile',
    height: 'Height(in)',
    width: 'Width(in)',
    depth: 'Depth(in)',
    clearance_top: 'Top Clearance(in)',
    clearance_bottom: 'Bottom Clearance(in)',
    clearance_right: 'Right Clearance(in)',
    clearance_left: 'Left Clearance(in)',
    clearance_front: 'Front Clearance(in)',
    clearance_back: 'Back Clearance(in)',
    weight: 'Weight(lb)',
    loaded_weight: 'Loaded Weight(lb)',
    ship_weight: 'Ship Weight(lb)',
    comment: 'Comment',
    cut_sheet: 'Spec',
    has_shop_drawing: 'Shop Drawing',
    cad_block: 'CAD Block',
    revit: 'Revit',
    discontinued: 'Disc',
    lead_time: 'Lead Time',
    estimated_delivery_date: 'Install Date',
    asset_profile: 'Profile',
    tag: 'TAG',
    placement: 'Placement',
    ecn: 'ECN',
    biomed_check_required: 'Biomed Check Required',
    current_location: 'Status',
    po_status_none: 'None PO',
    po_status_open: 'PO Open',
    po_status_issued: 'PO Issued',
    po_status_requested: 'PO Requested',
    po_status_qrequested: 'Quote Requested',
    po_status_qreceived: 'Quote Received',
    lease_qty: 'Lease qty',
    dnp_qty: 'DNP qty',
    net_new: 'Net New',
    total_unit_budget: 'Unit Budget (Net)',
    total_budget_amt: 'Total Budget (Net)',
    po_qty: 'PO qty',
    total_po_amt: 'PO amt',
    buyout_delta: 'PO delta',
    quote_number: 'Quote Number',
    po_requested_number: 'Requisition Number',
    vendor: 'Vendor',
    unit_markup: 'Unit Markup (%)',
    unit_markup_calc: 'Unit Markup ($)',
    unit_escalation: 'Unit Escalation (%)',
    unit_escalation_calc: 'Unit Escalation ($)',
    unit_budget_adjusted: 'Unit Budget(Adjusted)',
    unit_tax: 'Unit Tax (%)',
    unit_tax_calc: 'Unit Tax ($)',
    unit_install_net: 'Unit Install (Net)',
    unit_install_markup: 'Unit Install Markup (%)',
    unit_install: 'Unit Install',
    unit_freight_net: 'Unit Freight (Net)',
    unit_freight_markup: 'Unit Freight Markup (%)',
    unit_freight: 'Unit Freight',
    unit_budget_total: 'Unit Budget',
    all_units_cost: 'Total Budget (Net)',
    total_budget_adjusted: 'Total Budget (Adjusted)',
    total_tax: 'Total Tax ($)',
    total_install_net: 'Total Install (Net)',
    total_install: 'Total Install',
    total_freight_net: 'Total Freight (Net)',
    total_freight: 'Total Freight',
    total_budget: 'Total Budget',
    po_number: 'PO Number',
    delivered_date: 'Delivered Date',
    received_date: 'Received Date',
    option_codes: 'Options Code',
    option_descriptions: 'Options Description',
    options_price: 'Options Price',
    it_connections: 'IT Connections',
    class: 'Class',
    clin: 'CLIN',
    jsn_nomenclature: 'JSN Nomenclature',
    jsn_description: 'JSN Description',
    jsn_comments: 'JSN Comments',
    jsn_utility1: 'U1',
    jsn_utility2: 'U2',
    jsn_utility3: 'U3',
    jsn_utility4: 'U4',
    jsn_utility5: 'U5',
    jsn_utility6: 'U6',
    cost_center: 'Cost Center',
    inventory_id: 'Inventory ID',
    asset_total_budget: 'Asset Total Budget'
});