xPlanner.constant('AssetColumnsName', {
    asset_code: 'Code',
    photo: 'Photo',
    model_number: 'Model No.',
    model_name: 'Model Name',
    asset_description: 'Description',
    manufacturer_description: 'Manufacturer',
    asset_category: 'Category',
    asset_subcategory: 'Subcategory',
    owner_name: 'Owner',
    comment: 'Comment',
    cut_sheet: 'Spec',
    cad_block: 'CAD Block',
    revit: 'Revit',
    uploaded_at: 'Last Update',
    discontinued: 'Disc',
    alternate_asset: 'Alternate Asset',
    medgas: 'Gases description',
    medgas_option: 'Gases required',
    medgas_oxygen: 'Oxygen',
    medgas_air: 'MedAir',
    medgas_n2o: 'N2O',
    medgas_co2: 'CO2',
    medgas_wag: 'WAG',
    medgas_other: 'Air Low Pressure',
    medgas_high_pressure: 'Air High Pressure',
    medgas_nitrogen: 'Nitrogen',
    medgas_vacuum: 'Vacuum',
    medgas_steam: 'Steam',
    medgas_natgas: 'NatGas',
    gas_acetylene: 'Acetylene',
    gas_butane: 'Butane',
    gas_hydrogen: 'Hydrogen',
    gas_instrument_air: 'Instrument Air',
    gas_liquid_co2: 'Liquid CO2',
    gas_liquid_nitrogen: 'Liquid Nitrogen',
    gas_liquid_propane_gas: 'Liquid Propane Gas',
    gas_methane: 'Methane',
    gas_propane: 'Propane',
    misc_antimicrobial: "Antimicrobial",
    misc_ecolabel: "Eco-Label",
    misc_ecolabel_desc: "Eco-Label Description",
    plumbing: "Pumbling Description",
    plumbing_option: "Plumbing Required",
    plu_hot_water: "Hot Water",
    plu_cold_water: "Cold Water",
    plu_drain: "Drain",
    plu_return: "Return",
    plu_treated_water: "Treated Water",
    plu_chilled_water: "Chilled Water",
    plu_relief: "Relief",
    water: "Exhaust Description",
    water_option: "Exhaust Required",
    cfm: "CFM",
    btus: "BTUs",
    data_desc: "Data Description",
    data_option: "Data Required",
    network_option: "Network Required",
    network_type: "Network Type",
    electrical: "Electrical Description",
    electrical_option: "Electrical Required",
    volts: "Volts",
    phases: "Phases",
    hertz: "Hertz",
    amps: "Amps",
    volt_amps: "VoltAmps",
    watts: "Watts",
    blocking: "Blocking Description",
    blocking_option: "Blocking Required",
    supports: "Structural Description",
    supports_option: "Structural Required",
    misc_seismic: "Seismic Rated",
    misc_ase: "ASE",
    misc_ada: "ADA",
    misc_shielding_lead_line: "Shielding, Lead Lined",
    misc_shielding_magnetic: "Shielding, RF/Magnetic",
    mobile: "Mobile Description",
    mobile_option: "Mobile",
    height: "Height(in)",
    width: "Width(in)",
    depth: "Depth(in)",
    clearance_top: "Top Clearance(in)", 
    clearance_bottom: "Bottom Clearance(in)",
    clearance_right: "Right Clearance(in)",
    clearance_left: "Left Clearance(in)",
    clearance_front: "Front Clearance(in)",
    clearance_back: "Back Clearance(in)",
    weight: "Weight(lb)",
    loaded_weight: "Loaded Weight(lb)",
    ship_weight: "Ship Weight(lb)",
    vendors_model: 'Vendors Model'
});