xPlanner.constant('StatesList', [
                { id: "AK", abrv: "AK", name: "Alaska" },
                { id: "AL", abrv: "AL", name: "Alabama" },
                { id: "AR", abrv: "AR", name: "Arkansas" },
                { id: "AZ", abrv: "AZ", name: "Arizona" },
                { id: "CA", abrv: "CA", name: "California" },
                { id: "CO", abrv: "CO", name: "Colorado" },
                { id: "CT", abrv: "CT", name: "Connecticut" },
                { id: "DE", abrv: "DE", name: "Delaware" },
                { id: "FL", abrv: "FL", name: "Florida" },
                { id: "GA", abrv: "GA", name: "Georgia" },
                { id: "HI", abrv: "HI", name: "Hawaii" },
                { id: "IA", abrv: "IA", name: "Lowa" },
                { id: "ID", abrv: "ID", name: "Idaho" },
                { id: "IL", abrv: "IL", name: "Illinois" },
                { id: "IN", abrv: "IN", name: "Indiana" },
                { id: "KS", abrv: "KS", name: "Kansas" },
                { id: "KY", abrv: "KY", name: "Kentucky" },
                { id: "LA", abrv: "LA", name: "Louisiana" },
                { id: "MA", abrv: "MA", name: "Massachusetts" },
                { id: "MD", abrv: "MD", name: "Maryland" },
                { id: "ME", abrv: "ME", name: "Maine" },
                { id: "MI", abrv: "MI", name: "Michigan" },
                { id: "MN", abrv: "MN", name: "Minnesota" },
                { id: "MO", abrv: "MO", name: "Missouri" },
                { id: "MS", abrv: "MS", name: "Mississippi" },
                { id: "MT", abrv: "MT", name: "Montana" },
                { id: "NC", abrv: "NC", name: "North Carolina" },
                { id: "ND", abrv: "ND", name: "North Dakota" },
                { id: "NE", abrv: "NE", name: "Nebraska" },
                { id: "NH", abrv: "NH", name: "New Hampshire" },
                { id: "NJ", abrv: "NJ", name: "New Jersey" },
                { id: "NM", abrv: "NM", name: "New Mexico" },
                { id: "NV", abrv: "NV", name: "Nevada" },
                { id: "NY", abrv: "NY", name: "New York" },
                { id: "OH", abrv: "OH", name: "Ohio" },
                { id: "OK", abrv: "OK", name: "Oklahoma" },
                { id: "OR", abrv: "OR", name: "Oregon" },
                { id: "PA", abrv: "PA", name: "Pennsylvania" },
                { id: "RI", abrv: "RI", name: "Rhode Island" },
                { id: "SC", abrv: "SC", name: "South Carolina" },
                { id: "SD", abrv: "SD", name: "South Dakota" },
                { id: "TN", abrv: "TN", name: "Tennessee" },
                { id: "TX", abrv: "TX", name: "Texas" },
                { id: "UT", abrv: "UT", name: "Utah" },
                { id: "VA", abrv: "VA", name: "Virginia" },
                { id: "VT", abrv: "VT", name: "Vermont" },
                { id: "WA", abrv: "WA", name: "Washington" },
                { id: "WI", abrv: "WI", name: "Wisconsin" },
                { id: "WV", abrv: "WV", name: "West Virginia" },
                { id: "WY", abrv: "WY", name: "Wyoming" }
]);