CREATE TABLE [dbo].[jsn]
(
	[Id] INT IDENTITY (1, 1) NOT NULL , 
	[domain_id] SMALLINT NOT NULL,
    [jsn_code] VARCHAR(5) NOT NULL, 
    [nomenclature] VARCHAR(300) NOT NULL, 
    [mhs_cat] VARCHAR NULL, 
    [va_cat] VARCHAR(10) NULL, 
    [fundsourmhs] VARCHAR(10) NULL, 
    [fundsourva] VARCHAR(3) NULL, 
    [amps1] INT NULL, 
    [amps2] INT NULL, 
    [archived] BIT NULL, 
    [assigned_individual] VARCHAR(10) NULL, 
    [btuperhour] INT NULL, 
    [cen_depth] INT NULL, 
    [cen_height] DECIMAL(10, 2) NULL, 
    [cen_width] DECIMAL(10, 2) NULL, 
    [comments] VARCHAR(1000) NULL, 
    [date_appr] DATE NULL, 
    [description] VARCHAR(MAX) NULL, 
    [freq_review] INT NULL, 
    [hertz] VARCHAR(10) NULL, 
    [hertz_dep] VARCHAR(10) NULL, 
    [hertz_swit] VARCHAR(10) NULL, 
    [in_depth] DECIMAL(10, 2) NULL, 
    [inches_height] DECIMAL(10, 2) NULL, 
    [inches_width] DECIMAL(10, 2) NULL, 
    [last_modified] DATE NULL, 
    [nsn] VARCHAR(50) NULL, 
    [pending] BIT NULL, 
    [phase1] INT NULL, 
    [phase2] INT NULL, 
    [unit_issue] VARCHAR(2) NULL, 
    [utility1] VARCHAR(10) NULL, 
    [utility2] VARCHAR(10) NULL, 
    [utility3] VARCHAR(10) NULL, 
    [utility4] VARCHAR(10) NULL, 
    [utility5] VARCHAR(10) NULL, 
    [utility6] VARCHAR(10) NULL, 
    [utility7] VARCHAR(10) NULL, 
    [volts] VARCHAR(20) NULL, 
    [watts] VARCHAR(20) NULL, 
    [wct_csi_link] VARCHAR(50) NULL, 
    [weight_av] DECIMAL(10, 2) NULL, 
    [weight_met] DECIMAL(10, 2) NULL, 
    [year_review] VARCHAR(4) NULL, 
    [asset_code] VARCHAR(3) NULL, 
    [asset_code_domain_id] SMALLINT NULL, 
    [date_added]             DATE   DEFAULT (getdate()) NULL,
    [added_by]               VARCHAR (50)    NULL,
    [deprecated]               BIT DEFAULT ((0)) NULL,
    PRIMARY KEY ([Id], [domain_id]), 
    CONSTRAINT [fk_jsn_domain] FOREIGN KEY ([domain_id]) REFERENCES [dbo].[domain]([domain_id]),
	CONSTRAINT [uq_jsn_domain] UNIQUE NONCLUSTERED([jsn_code], [domain_id])
)

GO

CREATE NONCLUSTERED INDEX [AddedByIndex] ON [dbo].[jsn] ([added_by])
GO
CREATE NONCLUSTERED INDEX [JsnCodeIndex] ON [dbo].[jsn] ([jsn_code])
